CLUSTAL multiple sequence alignment by MUSCLE (3.8)


Plecturocebus      GTTAATGTAGCTTAAT-ACTCAAAGCAAGACACTGAAAATGTCTAGACGGGTGACTAC-A
Callithrix         GTTGATGTAGCTTAAT--TTTAAAGCAAGACACTGAAAATGTCTAGACGGGTGGTCACAA
Alouatta           GTTAATGTAGCTTAACAATTTAAAGCAAGACACTGAAAATGTCTAGATGGGTAACACCTA
                   *** ***********    * ************************** ****     * *

Plecturocebus      CCCCATAAACACACAGGTTTGGTCCTGGCCTTTCTATTAGCTCTCAGTAAGACTACACAT
Callithrix         CCCCATAAACACATAGGTTTGGTCCTAGCCTTTCTATTGGCCCTCAGTGATATTACACAT
Alouatta           CCCCATAAACACATAGGTTTGGTCCTAGCCTTTCCATTAGCTCTCAGTAAAATTACACAT
                   ************* ************ ******* *** ** ****** * * *******

Plecturocebus      GCAAGCATCCACGGCCCTGTGAGAATGCCCTCCAGACTACAA-AACAAGAGGAGCAAGTA
Callithrix         GCAAGCATCCACGACCCTGTGAGAATGCCCTCC-----ACCAAGATGTGAGGAGCAAGTA
Alouatta           GCAAGCATCCACAATCCTGTGAAAATGCCCTCTAGATTACAATAACATGAGGAGCGAGCA
                   ************   ******* *********      ** *  *   ******* ** *

Plecturocebus      TCAAGCACGC--ACAAGCAGCTCAAAACACTTTGCTCAGCCACACCCCCACGGGAAACAG
Callithrix         TCAAGCACGCAAACATGCAGCTCAAGACACTTTGCTTAGCCACACCCCCACGGGAGACAG
Alouatta           TCAAGCACGC--ACACGCAGCTCAAAACGCTTTGCTTAGCCACGCCCCCACGGGAAACAG
                   **********  *** ********* ** ******* ****** *********** ****

Plecturocebus      CAGTGACTAACCTTTAGCAATAAACGAAAGTTTAACTAAGTTATACTGACACCCAGAGTC
Callithrix         CAGTGACAAACTTTTAGCAATGAACGAAAGTTTAACTAAGTTACACTGACAATCAGAGTT
Alouatta           CAGTGATAGACCTTTAGCAATAAACGAAAGTTTAACTAAGTTATACTGATTATTAGAGTT
                   ******   ** ********* ********************* *****     ***** 

Plecturocebus      GGTCAATTTCGTGCCAGCCACCGCGGCCATACGATTGACTCAAGTTAATAGAGTCCGGCG
Callithrix         GGTCAATTTCGTGCCAGCCACCGCGGCCATACGATTGACTCGAGTTAATAGAGCCCGGCG
Alouatta           GGTCAATTTCGTGCCAGCCACCGCGGCCATACGATTGACTCAAGTTAATAGAGTACGGCG
                   ***************************************** ***********  *****

Plecturocebus      TAAAGAGTGTTTAAGACTTA---CTATTAATAAAGCTAACCTGTAACTAAGTTGTAGAAA
Callithrix         TAAAGAGTGTTTAAGATTTAGCCCGCCCAATAAAGCTAACCTATAACTAAGTCGTAGAAA
Alouatta           TAAAGAGTGTTTAAGACT--ATTCCTTCAATAAAGCTAACCTATAACTAAGTCGTAAAAA
                   **************** *     *    ************** ********* *** ***

Plecturocebus      ACCCTGGTTATGGTAAAATATCCTACGAAAGTGGCTTTATTATCCTGAACACACTATAGC
Callithrix         ACTCCGGTTATAGTGAAATATTCTACGAAAGTGGCTTTAGCATTCTGAACACACTATAGC
Alouatta           ACCCTGGTTATGGTAAAATATTCTACGAAAGTGGCTTTAATACCCTGAATACACTAAAGC
                   ** * ****** ** ****** *****************  *  ***** ****** ***

Plecturocebus      TAAGGTACAAACTGGGATTAGATACCCCACTATGCTTAGCCCTAAACTTCAATAACTTAA
Callithrix         TAAGACACAAACTGGGATTAGATACCCCACTATGCTTAGCCCTAAACCTCAATAATTTAA
Alouatta           TAAGGCACAAACTGGGATTAGATACCCCACTATGCTTAGCCCTAAACCTCAATAACTTAA
                   ****  ***************************************** ******* ****

Plecturocebus      TTAACAAAATTATTCGCCAGAACACTACAAGCCACAGCTTGAAACTCAAAGGACCTGGCG
Callithrix         TTAACAAATTTATTCGCCAGAACACTACAAGCAACAGCTTGAAATTCAAAGGACCTGGCG
Alouatta           TCAACAAACTTATTCGCCAGAACACTACAAGCAACAGCTTGAAACTCAAAGGACCTGGCG
                   * ****** *********************** *********** ***************

Plecturocebus      GTGCTTTATATCCTTCTAGAGGAGCCTGTTCTGTAATCGATAAACCCCGATAAACCTCAC
Callithrix         GTGCTTTACATCCGTCTAGAGGAGCCTGTTCTATAATCGATACACCCCGATAAACCTCAC
Alouatta           GTGCTTTACATCCGTCTAGAGGAGCCTGTTCTATAATCGATATACCCCGATAAACCTTAC
                   ******** **** ****************** ********* ************** **

Plecturocebus      CACCCCTTGCC-CTCAGCCTGTATACCGCCATCTTCAGCAAACTCCCTAAAGACAGCATA
Callithrix         CACATCTAGCCACTCAGCCTGTATACCGCCATCTTCAGCAAACTCCTTAATGATTGCAAA
Alouatta           CACCCCTTGCC-CCCAGCCTGTATACCGCCATCTTCAGCAAACTCCCTAAAGATCGCAAA
                   ***  ** *** * ******************************** *** **  *** *

Plecturocebus      GTAAGCAGAAGTATTATCATAAAAACGTTAGGTCAAGGTGCAGCCAATGGGGCGGG-AGT
Callithrix         GTAAGCAGAAGTATCATCATAAAAACGTTAGGTCAAGGTGCAGCCAATGACGTGGGAAGA
Alouatta           GTAAGCAGAAGTATTATCATAAAAACGTTAGGTCAAGGTGCAGCCAATGAGGTGGGAAGA
                   ************** **********************************  * *** ** 

Plecturocebus      AATGGGCTACATTTTCTAAATCAGAAAATCACACGACAGCCTTTATGAAATTTAAAGTCC
Callithrix         AATGGGCTACATTTTCTACATCAGAAAACTAAACGATAACCCTTATGAAATTTAAGGGCC
Alouatta           AATGGGCTACATTTTCTAAATCAGAAAATTACACGACAACCTTTATGAAATCTAAAGGTC
                   ****************** *********  * **** * ** ********* *** *  *

Plecturocebus      CAAGGTGGATTTAGCAGTAAATCAAGAATAGAGAGCTTGATTGAAGTAAGGCCATTAAGC
Callithrix         TAAGGTGGATTTAGCAGTAAACCAAGAATAGAGAGCTTGGTTGAAACAAGGCCATTAAGC
Alouatta           CAAGGTGGATTTAGCAGTAAATCAAGAACAGAGAGCTTGATTGAAACAAGGCCATTAAGC
                    ******************** ****** ********** *****  *************

Plecturocebus      ACGCACACACCGCCCGTCACCCTCCTCAAACATCACACTAATAGTGCACTAACAAC-AAA
Callithrix         ACGCACACACCGCCCGTCACCCTCCTCAAACATCACAC-AAAAGTATATTAACAACTAAG
Alouatta           ACGCACACACCGCCCGTCACCCTCCTCAAACATCACAC-AAAAGTACTTTAACAACTAAA
                   ************************************** ** ***    ******* ** 

Plecturocebus      CAACTATACGCTGATATAGAGGGGATAAGTCGTAACATGGTAAGCGTACTGGAAAGTGCG
Callithrix         CCACTTCACACTGATCTAGAGGGGATAAGTCGTAACATGGTAAGCGTACTGGAAAGTGCG
Alouatta           TCACTATATATTGATATAGAGGGGATAAGTCGTAACATGGTAAGCGTACTGGAAAGTGCG
                     ***  *   **** ********************************************

Plecturocebus      CTTGGATAAACCAAAGCGTAGCTTAAACTAAAGCATCCAGCTTACACCCGGAAGATATCG
Callithrix         CTTGGACGAACCAAAACGTAGCTTAAATTAAAGCATCCGGCTTACACCCGGAAGATCTCA
Alouatta           CTTGGGTAAATCAAAGTGTAGCTTAAATCAAAGCATCCGGCTTACACCCAGAAGATCTCA
                   *****   ** ****  **********  ********* ********** ****** ** 

Plecturocebus      CAAATAGCCGATCGCTCTGAGCTAATTCTAGCCCAAACCATAA-ACTATTATACTATCCA
Callithrix         C-AACAAATGATCGTTTTGAGCTAACCCTAGCCCAAACACTACTAAAAC-ATACTACTTA
Alouatta           CTCACCGATGATCACTTTGAGCCAACTCTAGCCCAAACCCCCATACAACTGTACTACCTA
                   *  *     ****  * ***** **  ***********      *  *   *****   *

Plecturocebus      -ATCATACCAATTAAATCATTTACCCATTGCAAAAGTATAGGTGATAGAAATTG-AACTT
Callithrix         -ACCTCATTAATTAAATCATTTACCTACTACAAAAGTATAGGAGATAGAAATTATATTTT
Alouatta           CAATACTACAACTAAACCATTTACCTATTATAAAAGTATAGGCGATAGAAATTTCACCTT
                    *       ** **** ******** * *  *********** **********  *  **

Plecturocebus      AGGCGCAATAGATACAGTACCGCAAGGGAAAGA-CAAATCTCCACAAAGCATAAAAAAGC
Callithrix         AGGCGCAATAGATGCAGTACCGCAAGGGAAAGAACAAAAC-CAATGAAGCACAAAAAAGC
Alouatta           AGGCGCAATAGATATAGTACCGCAAGGGAAAGACAAAAACTTAATGAAGCATAAAAAAGC
                   *************  ******************  *** *   *  ***** ********

Plecturocebus      AAAGATAAACCCTTCTACCTTTTGCATAATGAATTAACTAGAAATTATATTGTATAAAGA
Callithrix         AAAGATATGCCCTTATACCTTCTGCATAATGAACCAACTAGAAATAGCTCTATAAAGAGA
Alouatta           AAAGACAAACCCTTTTACCTTCTGCATAATGAATTAATTAGAAATGACTTTATATAGAGA
                   ***** *  ***** ****** ***********  ** *******     * ** * ***

Plecturocebus      ACTTCAATAATACTCCCCGAAACCAAGCGAGCTACCCACGGACAGCT-AAAGAGCATACC
Callithrix         ACTTAAATAATGCCCCCCGAAACCAAGCGAGCTACCCAAAGATAGCTAAAAGAGCGCACC
Alouatta           ACTTTAATAATGCCCCCCGAAACCAAGCGAGCTACCCAAAGACAGCTAAAAGAGCACACC
                   **** ****** * ************************  ** **** *******  ***

Plecturocebus      CGTCTATGTGGCAAAATAGTGGGAAGATCTGCGGGTAGAGGCGACAAACCTACCGAGCTT
Callithrix         CGTCTATGTGGCAAAATAGTGGGAGAATCTCTGGGTAGTGGCGACAAACCTACCGAGCCT
Alouatta           CGTCTATGTGGCAAAATAGTGGGAAGATCTATGGGTAGTGGTGACAAACCTATCGAGCCT
                   ************************  ****  ****** ** ********** ***** *

Plecturocebus      GGTGATAGCTGGTTATCCAAGACAGAATTTCAGTTCAACTTTAAATTTACTCACAGAACT
Callithrix         GGTGATAGCTGGTTGTCCAAGACAGAATCTTAGTTCAACTTTAAATTTGCCTGCAGAATC
Alouatta           GGTGATAGCTGGTTGTCCAAGACAGAATTTTAGTTCAACCTTAAATTTACTTACAGATCC
                   ************** ************* * ******** ******** *   ****   

Plecturocebus      -CCTAATCCTCCCGTAAATTTAATAGTTACTCTAAAGAGGGACAGCTCTTTAGACTATAG
Callithrix         ATATAATCCCCCTGTAAATTTAACTGTTAGTCTAAAGAGGGACAGCTCTTAAGACCCTAG
Alouatta           ACCTAATCTTCTCGTAAATTTAATTGTTAATCTAAAGAGGGACAGCTCTTTAGACTTTAG
                      *****  *  **********  **** ******************** ****  ***

Plecturocebus      GAAACAACCTTATATAGAGAGTAAAACACCTAATTACTACAGTAGGCTTTAAAGCAGCCA
Callithrix         GAAACAACCTTTTATAGAGAGTAAACAATTTAACCACCATAGTTGGCCTAAAAGCAGCCA
Alouatta           GAAATAACCTTTTATAGAGAGTAAGCTATTCCACCACTACAGTTGGCCTAAAAGCAGCCA
                   **** ****** ************   *    *  ** * *** *** * **********

Plecturocebus      CCAATTAAGAAAGCGTTCAAGCTCAACACCCTTACTCCCCTAATTCCACCCATTTTACTG
Callithrix         CCAATTAAGAAAGCGTTAAAGCTCAATATTTACTTACTCTTAATCCTAATAATCCCATTG
Alouatta           TCAATTAAGAGTGCGTTCAAGCTCAATACCTAATTATCCTTAATTCTACTAATAATATCA
                    *********  ***** ******** *          * **** * *   **   *   

Plecturocebus      AACTCCTATAATATATTGGATTAATCTATTTCCAAATAGAGGCAATAATGTTAGTATAAG
Callithrix         AACTCCTAATACAAATTGGACTAATCTATTATCAAATAGAAGCAATAATGTTGATATAAG
Alouatta           AACTCCTATAACACATTGGACTAATCTATTATCCAATAGAAGCAACAATATTAGTATAAG
                   ********  * * ****** *********  * ****** **** *** **  ******

Plecturocebus      TAACATGAAATTATTCTCCTTGCATAAGCTTATCCCAGACCGGAACTACCACTGCTAGTT
Callithrix         TAACATGAAATTATTCTCCTTGCATAAGCTTATCTCAGACCGAAACAACTACTGTTAGTT
Alouatta           TAACATGAAATTATTCTCCCCGCATAAACTTATCTCAGACCGAAACAACTACTGCTAGTT
                   *******************  ****** ****** ******* *** ** **** *****

Plecturocebus      AACAGCCAAATCACCTTACCCCACAACCTCATCTGCCCATTACCCCAACTGTTAACCCAA
Callithrix         AACAGCCCAATTACCATATACTACAAATTAACTCATCAATTAACTGAACTGTTAACCCGA
Alouatta           AACAGTTCAATCACTATATACTATATCTTAACATAAC-ATTACTTAAACTGTTAACCCAA
                   *****   *** **  **  * * *   * *     * ****    ************ *

Plecturocebus      CACAGGCATGCTATTCAGGAAAGATTAAAAAAAGTAAAAGGAACTCGGCAAACTCTACCC
Callithrix         CACAGGCATGC-ACTAAGGAAAGATCAAAAAAAGTAAAAGGAACTCGGCAAACTCTACCC
Alouatta           CACAGGTATGC-ACCCAGGAAAGATTAAAAGAAGTAAGAGGAACTCGGCAAACTCTACCC
                   ****** **** *   ********* **** ****** **********************

Plecturocebus      CCGCCTGTTTACCAAAAACATCACCTCTAGCATAAACAGTATTAGAGGCACTGCCTGCCC
Callithrix         CCGCCTGTTTACCAAAAACATCACCTCTAGCATCCCCAGTATTAGAGGCACTGCCTGCCC
Alouatta           CCGCCTGTTTACCAAAAACATCACCTCTAGCATCACTAGTATTAGAGGCACTGCCTGCCC
                   *********************************    ***********************

Plecturocebus      AGTGACACATGTTCAACGGCCGCGGTACCCTGACCGTGCAAAGGTAGCATAATCACTTGT
Callithrix         AGTGACACATGTTCAACGGCCGCGGTACCCTGACCGTGCAAAGGTAGCATAATCACTTGT
Alouatta           GGTGACACATGTTTAACGGCCGCGGTACCCTGACCGTGCAAAGGTAGCATAATCACTTGT
                    ************ **********************************************

Plecturocebus      TCTCTAAATAAGGACTTGTATGAACGGCCACACGAGGGTTTAACTGTCTCTTACTTTTAA
Callithrix         TCTCTAAATAAGGACTTGTATGAATGGCCACACGAGGGTTCAACTGTCTCTTACTTTTAA
Alouatta           TCTCTAAATAAGGACTTGTATGAATGGCCACACGAGGGTTTAACTGTCTTTTACTTCTAA
                   ************************ *************** ******** ****** ***

Plecturocebus      TCAGTGAAATTGACCTATCCGTGAAGAGGCGGATATATTTAAATAAGACGAGAAGACCCT
Callithrix         TCAGTGAAATTGACCTATCCGTGAAGAGGCGGATATGCCCAAATAAGACGAGAAGACCCT
Alouatta           TCAGTGAAATTGACCTATCCGTGAAGAGGCGGATATAACTAAATAAGACGAGAAGACCCT
                   ************************************    ********************

Plecturocebus      ATGGAGCTTTAATTTAATAGTACAAACTAGTAGCTTAAAAACCCACAGGCATTAAATTAC
Callithrix         ATGGAGCTTCAATTTAATGGTACAAACCTCAACCCTTCAAACCAACAGGCAGTAGCCTAT
Alouatta           ATGGAGCTTAAATTTAATAGTACAAACTAACAATCTAAAAACCAATAGGCAATAACCCAC
                   ********* ******** ********    *   *  ***** * ***** **    * 

Plecturocebus      AGTCCATGTACTATAAATTTCGGTTGGGGTGACCTCGGAGCATAATACAACCCCCGAGAA
Callithrix         AATAGATGTACCATAAATTTTGGTTGGGGTGACCTCGGAGTACAATATAGCCCCCGAAAA
Alouatta           CGTCCATGAACTATAAATTTTGGTTGGGGTGACCTCGGAGTATAATATAACCCCCGAAAA
                     *  *** ** ******** ******************* * **** * ******* **

Plecturocebus      ATATACACCAAGACCTTACTAGTCTAAGTGA--GCCTATATTCATTGACCCAATAAATTG
Callithrix         ACACATACTAAGACCTCACCAGTCTAAGTAA--AAATAAATCTATTGACCCAATAGCTTG
Alouatta           ACATATACCAAGACCTCACCAGTCTAAGTAAATACTTACACCCATTGACCCAATAACTTG
                   * * * ** ******* ** ********* *     ** *   ************  ***

Plecturocebus      ATCAACGGACCAAGTTACCCTAGGGATAACAGCGCAATCCTATTACAGAGTCCATATCGA
Callithrix         ATCAACGGACTAAGTTACCCTAGGGATAACAGCGCAATCCTATTCTAGAGTCCATATCGA
Alouatta           ATCAACGGACTAAGTTACCCTAGGGATAACAGCGCAATCCTATTTTAGAGTCCATATCGA
                   ********** *********************************  **************

Plecturocebus      CAATAGGGTTTACGACCTCGATGTTGGATCAAGACATCCTAGTGGTGCAGCCGCTACTAA
Callithrix         CAATAGGGTTTACGACCTCGATGTTGGATCAAGACATCCTAATGGTGCAGACGCTATTAA
Alouatta           CAATAGGGTTTACGACCTCGATGTTGGATCAAGACATCCTAATGGTGCAGCCGCTATTAA
                   ***************************************** ******** ***** ***

Plecturocebus      AGGTTCGTTTGTTCAACGATTAAAGTCTTACGTGATCTGAGTTCAGACCGGAGTAATCCA
Callithrix         GGGTTCGTTTGTTCAACGATTAAAGTCTTACGTGATCTGAGTTCAGACCGGAGTAATCCA
Alouatta           GGGTTCGTTTGTTCAACGATTAAAGTCTTACGTGATCTGAGTTCAGACCGGAGAAATCCA
                    **************************************************** ******

Plecturocebus      GGTCGGTTTCTATCTATTAAATATTTCTCCCAGTACGAAAGGACAAGAGAAATAGGGCCC
Callithrix         GGTCGGTTTCTATCTATTAAATATTCCTCCCAGTACGAAAGGACAAGAGAAATGGGGCCC
Alouatta           GGTCGGTTTCTATCTATTAAATATTCCTCCCAGTACGAAAGGATAAGAGAAATAGAGCCT
                   ************************* ***************** ********* * *** 

Plecturocebus      ACTTTTCATAAGCGCCCTCACAAACCTAATGACTTCCATCTTAATTTTATAATTTCCTAC
Callithrix         ACTTCATA-AAGCGCCCTCAAGAATTAGATGACCCATATCTCAATCTCACATACTACAAC
Alouatta           ACTTCACA-AAGCGCCCTCACTAATTGGATGATCATTATCTCAATCCCATAAACTACTAC
                   ****   * ***********  **    ****     **** ***   * *   * * **

Plecturocebus      CC--GCCCTAAACCAGGGCTT-GTTAAGGTGGCAGAGCCCGGTAATTGCATAAAACTTAA
Callithrix         AT-AGCCCAAGAACAGGGCTTAGTTAAGATGGCAGAGCCCGGTAATTGCATAAAACTTAA
Alouatta           CCCACCCCAAGAACAGGGTTC-GTTAAGATGGCAGAGCCCGGTAATTGCATAAAACTTAA
                        *** * * ***** *  ****** *******************************

Plecturocebus      AACTTTATCACCAGAGGTTCAACTCCTCTCCTTAACAACTTGTTCATAATTAATTTACTC
Callithrix         AACTTTACACCCAGAGGTTCAACTCCTCTTCTTAACAACGTGTTTATACTCAACTTAATT
Alouatta           AACTTTATAACCAGAGGTTCAACTCCTCTTCTTAACAACGTGTTTATAATTAACTTACTC
                   *******   ******************* ********* **** *** * ** *** * 

Plecturocebus      CTACTTATTATCCCAGCCCTTATCGCCATAGCATTTCTTACACTTACAGAACGAAAAATC
Callithrix         CTACTAATCGTACCTGCCCTAATCGCTATAGCATTCCTGACACTTATAGAACGAAAAGTC
Alouatta           CTACTCGCCATCCCTGCCCTAATCGCCATAGCATTCTTAACACTTATAGAGCGGAAAGTC
                   *****     * ** ***** ***** ********  * ******* *** ** *** **

Plecturocebus      CTGGGCTATATACAATTCCGTAAAGGCCCTAACATTGTTGGCCCCTACGGAGTTCTTCAA
Callithrix         TTAGGTTATATACAATTACGGAAAGGACCAAACATTGTAGGGCCGTACGGAACACTCCAA
Alouatta           CTAGGTTATATACAATTTCGCAAAGGTCCTAACATGGTAGGCCCCTACGGAATACTTCAA
                    * ** *********** ** ***** ** ***** ** ** ** ******   ** ***

Plecturocebus      CCTATTGCAGACGCAATAAAACTCTTTACAAAAGAACCATTACTTCCCACAGCATCCACT
Callithrix         CCAATCGCCGACGCCATAAAACTTTTCACAAAAGAACCCCTACTACCTACTACTTCCACT
Alouatta           CCGTTCGCCGACGCAATAAAACTCTTTACAAAAGAACCTCTACTACCCACCACATCTACT
                   **  * ** ***** ******** ** ***********  **** ** **  * ** ***

Plecturocebus      ACAGTTCTATATGTAATTGCTCCAACCTTAGCACTCTCCATTGCCCTCCTCCTATGAGCC
Callithrix         GCAACTCTATATTTAACCGCCCCAACCTTAGCCCTCTCCATCGCCCTCCTTCTATGAGCG
Alouatta           ACAATCCTGTATGTAATTGCCCCAACCCTAGCCCTCTCCATCGCCCTCCTTATATGAAGT
                    **   ** *** ***  ** ****** **** ******** ********  *****   

Plecturocebus      CCTCTACCTATACCTCTCCCCCTAATCAATTTTAATCTAGGCCTCTTATTTATATTAGCA
Callithrix         CCACTTCCTATACCATACCCGCTAATTAATCTAAATCTAGGCCTCCTCTTTATTCTAGCA
Alouatta           CCCCTTCCCATACCATATCCTCTAATTAACTTCAACCTAGGCCTCCTATTTATACTAGCA
                   ** ** ** *****    ** ***** **  * ** ********* * *****  *****

Plecturocebus      ATCTCAAGCCTAGCTGTGTACTCAATTTTATGGTCCGGATGAGCGTCCAATTCAAAGTAT
Callithrix         ACATCAAGCCTAGCTGTTTATTCAATTCTATGGTCAGGCTGAGCATCCAACTCAAACTAT
Alouatta           ACATCAAGCCTAGCCGTATATTCAATCTTATGATCTGGATGAGCATCCAACTCAAACTAC
                   *  *********** ** ** *****  **** ** ** ***** ***** ***** ** 

Plecturocebus      GCTCTAATAGGTGCATTACGAGCCGTAGCCCAAACAATTTCATATGAAGTTACACTAGCT
Callithrix         GCACTAATTGGCGCATTACGAGCCGTGGCCCAAACAATCTCATACGAAGTCACCCTCGCC
Alouatta           GCACTAATCGGCGCATTACGAGCAGTAGCCCAAACAATTTCATACGAAGTTACCCTAGCC
                   ** ***** ** *********** ** *********** ***** ***** ** ** ** 

Plecturocebus      ATTATCCTCCTCTCCGTTCTACTAATAAGCGGCTCATTCAATCTACACTCACTTATTACA
Callithrix         ATCATCCTCCTATCCACCCTACTAATAAGCGGCTCATTCAATCTACAATCACTTATTACA
Alouatta           ATTATTCTACTATCAACCCTACTAATAAGCGGCTCATTCAACTTACACTCACTTATTACA
                   ** ** ** ** **    ***********************  **** ************

Plecturocebus      ACGCAAGAACACTTATGACTTCTCCTTCCATCATGACCTCTCGCCATAATATGATTTATT
Callithrix         ACACAAGAACACTACTGACTTCTACTCCCATCATGGCCCCTAGCCATGATATGATTTATC
Alouatta           ACACAAGAACACTCCTGACTTTTATTACCATCATGACCTTTAGCAATAATATGATTTATT
                   ** **********  ****** *  * ******** **  * ** ** *********** 

Plecturocebus      TCAACATTAGCCGAAACCAACCGAGCCCCCTTCGACCTAACAGAGGGCGAGTCAGAACTA
Callithrix         TCCACACTAGCAGAAACCAATCGAGCCCCCTTTGACCTCACTGAGGGCGAATCAGAACTA
Alouatta           TCTACACTAGCAGAAACCAATCGAGCTCCCTTCGACCTAACAGAAGGCGAATCAGAACTA
                   ** *** **** ******** ***** ***** ***** ** ** ***** *********

Plecturocebus      GTTTCAGGATTCAACATCGAATACGCCGCAGGCTCATTTGCCCTATTTTTCATAGCAGAA
Callithrix         GTCTCAGGCTTTAACATTGAATACGCCGCAGGCTCATTCGCCCTATTCTTTATAGCAGAG
Alouatta           GTTTCAGGGTTTAATATTGAATATGCTGCAGGTTCATTTGCCCTCTTCTTTATAGCAGAA
                   ** ***** ** ** ** ***** ** ***** ***** ***** ** ** ******** 

Plecturocebus      TATATAAACATCATCATAATAAACGCCTTAACCACCACCATCTTTTTAGCAGCACCCCAT
Callithrix         TATATAAATATTATTATAATAAATGCCCTAACCACCACCATCTTTCTAGCAACATCATTC
Alouatta           TACATAAATATTATTATAATAAACGCCCTAACCACCACCGTCTTCTTAGCTACACCCTAC
                   ** ***** ** ** ******** *** *********** ****  ****  ** *    

Plecturocebus      ACACTGCTTACCCCAGAATTATATACAGCAAACTTTATAACCAAAACACTTCTACTAACC
Callithrix         AACATAACCATATCAGAAATATACACAATCAACTTTATAACCAAAACCCTTCTACTAACC
Alouatta           AATATAAAATTACCAGAACTCTATACAACAAACTTTATAACCAAAGCCCTCCTACTAACT
                   *   *        ***** * ** ***   *************** * ** ******** 

Plecturocebus      ACATTATTCTTATGAATTCGAACAGCATATCCCCGATTCCGTTATGACCAACTTATACAT
Callithrix         ACCCTATTCCTATGAATTCGAACAGCATATCCTCGATTCCGCTATGACCAACTAATATAC
Alouatta           ATTCTATTTCTATGAATCCGAACATCATACCCTCGATTCCGCTATGATCAACTAATACAC
                   *   ****  ******* ****** **** ** ******** ***** ***** *** * 

Plecturocebus      CTCCTATGAAAAAAATTCTTACCCCTCACATTAGCACTATGTATATGGCATATCTCAATA
Callithrix         CTCCTATGAAAAAATTTCTTGCCTCTCACACTAGCACTATGTATGTGATACATCTCAGTA
Alouatta           CTTCTATGAAAAAACTTTTTACCTCTCACACTAGCACTATGCATATGATATGTCTCATTA
                   ** *********** ** ** ** ****** ********** ** **  *  ***** **

Plecturocebus      CCAATTCTTACATCTGCCGTACCTCCCCAAACAT-AGAAATATGTCTGACAAAAGAGTTA
Callithrix         CCCATCTTAATATCCGGCATCCCCCCACAAACATAAGAAATATGTCTGACAAAAGAGTTA
Alouatta           CCAACTCTAATATCCGGCATCCCACCCCAAACATAAGAAATATGTCTGACAAAAGAGTTA
                   ** *   * * *** * * * ** ** ******* *************************

Plecturocebus      CTTTGATAGAGTAAATTATAGAGGTTCAAATCCTCTTATTTCTAGAACTATAGGAGTTGA
Callithrix         CTTTGATAGAGTAAATTATAGAGGTTCAAACCCTCTTATTTCTAGGATTTTAGGAATTGA
Alouatta           CTTTGATAGAGTAAATTATAGAGGTTTAAATCCCCTTATTTCTAGAACTATAGGAGTTGA
                   ************************** *** ** *********** * * ***** ****

Plecturocebus      ACCCATACCTGAGAACTCAAAACTCTCCGTGCTACCTATTACACCACATTCTA---AGTA
Callithrix         ACCCATACCTGAGAACTCAAAACTCTCCGTGCTACCTATTACACCACATCCTAAACAGTA
Alouatta           ACCCATGCCTGAGAACTCAAAACTCTCCGTGCTACCTTCTACACCATATTCTAACTAGTA
                   ****** ******************************  ******* ** ***   ****

Plecturocebus      AGGTCAGCTAAATAAGCTATCGGGCCCATACCCCGAAAATGTTGGTTTCAATCCTTCCCG
Callithrix         AGGTCAGCTAAATAAGCTATCGGGCCCATACCCCGAAAATGTTGG-TTAAATCCTTCCCG
Alouatta           AGGTCAGCTAAATAAGCTATCGGGCCCATACCCCGAAAATGTTGG-TTAAACCCCTCCCG
                   ********************************************* ** ** ** *****

Plecturocebus      TACTAACATCAACCCTCTAGCCCAACTCATTATCTTCTTCACAATTTTAACAGGAACTTT
Callithrix         TACTAATATCAACCCCCTGGCCCACCTCATCATCTCCTTAACCATCCTAACAGGGTCCAC
Alouatta           TACTAACATCAACCCTCTAGCCTACCTCATTATTTTTCTTACTGTCCTAGCAGGAACCAT
                   ****** ******** ** *** * ***** ** *   * **  *  ** ****  *   

Plecturocebus      AATTACAATCCTAAGCTCACACTGATTCCTCATCTGAGTAGGACTAGAACTAAATATACT
Callithrix         AATCACTATTCTAAGCTCGCACTGATTTCTGGCCTGAATAGGTCTAGAACTGAATATACT
Alouatta           AATTACAATAATAAGCTCACACTGATTCCTAATCTGAATAGGCCTAGAATTAAATATACT
                   *** ** **  ******* ******** **   **** **** ****** * ********

Plecturocebus      AGCCATTGTTCCAGTACTAGCTAAGACTACAAATCCCCGCTCTACAGAAGCAGCTACAAA
Callithrix         AGCCATCGTACCAATTTTAGCCAAAAACACAAACCCACGATCCACAGAAGCTTCCACCAA
Alouatta           AGCCATCGTACCCCTGCTAGCCAAAAACACAAACCCCCGCTCCACAGAAGCAGCCACTAA
                   ****** ** **  *  **** ** *  ***** ** ** ** ********  * ** **

Plecturocebus      ATATTTCCTAATTCAAGCAACCGCATCCATGCTCCTCCTAATAATAATCTTTATAAACAA
Callithrix         ATATTTTTTAATCCAAGCAACAGCATCAATAATTCTCCTAATAGCCATCTTCCTTAATAA
Alouatta           ATATTTTCTAACACAAGCAACCGCATCCATAGTCCTACTAATAGCCATTTACCTAAATAA
                   ******  ***  ******** ***** **  * ** ******   ** *   * ** **

Plecturocebus      TCTGCTCTCCGGGCAGTGAACTATTAGTCCTCCCACAAGCCAATTCTTAACTACAATAAT
Callithrix         CCTAACCTCCGGGCAATGAACAATTAGCCCACCCCACAGCCAAATTCTATCTACGATAAT
Alouatta           TTTATTTTCCGGACAATGAACAATCTACCCATCCCTAAACCAAACCCTCGCTACAATAAT
                     *    ***** ** ***** **    **  **   * ****    *  **** *****

Plecturocebus      ATTAATTGCTTTGACAATAAAACTAGGCATGGCCCCTCTTCACTTCTGACTCCCAGAAGT
Callithrix         ATTAATCGCCCTAGTAATAAAAATAGGAATAGCCCCCCTCCACTTCTGACTTCCAGAAGT
Alouatta           ATTAATTGCCCTAACAATAAAATTAGGAATAGCCCCTCTTCACTTTTGATTGCCAGAAGT
                   ****** **  *   ******* **** ** ***** ** ***** *** * ********

Plecturocebus      AACCCAAGGTATTCCCCTTATTCCCGCCATAATTATTCTCACATGACAAAAACTAGCCCC
Callithrix         AACCCAAGGAACCCCCCTAATTCCAGCCATAATCGTCCTCACATGACAAAAACTTGCCCC
Alouatta           AACCCAAGGCATCCCCCTAATCCCTGCTATACTCATTCTCACATGACAAAAACTGGCCCC
                   ********* *  ***** ** ** ** *** *  * ***************** *****

Plecturocebus      TATTTCAATTATATTCCAAATCTTCCCATCCATTAATATAAATATCTTAATAGCAATTTC
Callithrix         CTTGTCAATTATATTTCAAATCTTCCCATCAACAAACACTAATATTATCCTAATAATCTC
Alouatta           CTTATCTATTATACTCCAAATCTTTTCATCAATTGACACCAATACCCTACTAATAATTTC
                     * ** ****** * ********  **** *   * *  ****   *  **  *** **

Plecturocebus      CATGTTATCAATTATAATTGGCAGCTGAGGCGGACTAAATCAAACACAATTACGCAAAAT
Callithrix         AATCCTATCAATTATGGCCGGCAGTTGAGGAGGACTTAATCAAACGCAACTACGAAAAAT
Alouatta           AATTTTATCTATTATAATTGGCAGCTGAGGTGGACTCAACCAAACACAATTACGTAAAAT
                    **  **** *****    ***** ***** ***** ** ***** *** **** *****

Plecturocebus      TATAGCCTACTCATCAATTACCCACATAGGGTGAATAATGGCAGTTCTACATTATAACCC
Callithrix         CCTAGCCTACTCCTCAATTACCCATATAGGATGAATAATAGCCGTACTATACTATGACCC
Alouatta           TCTAGCTTACTCCTCAATTACCCACATAGGATGAATAGTAGCAGTATTATATTACGACCC
                     **** ***** *********** ***** ****** * ** **  ** * **  ****

Plecturocebus      CAACATTACTATTCTTAGCCTACTTATCTACCTATTCCTAACAATCACTATCTTTATAAC
Callithrix         AAACATCACCGTTCTAACACTTATTATCTACATTTTCCTAACAATCTCCACATTCATAAT
Alouatta           AAATATTACAATCCTAACTCTATTCATCTATATCCTTCTAACAATCTCCACATTCATAAC
                    ** ** **  * ** *  **  * *****  *  * ********* * *  ** **** 

Plecturocebus      CTTTTATCTAAATTCAAATACAACAACCCTATCTATATCCCACACCTGAAATAAATTCAC
Callithrix         TTTTTACCTAAACTCAAACATAACAACCCTATCACTATCACATACCTGAAATAAATTAAC
Alouatta           TTTTTACCTGAACTCAAATACAACAACCCTATCACTATCACACACCTGAAATAAACTTAC
                    ***** ** ** ***** * ************  **** ** ************ * **

Plecturocebus      ATGAACTATACCTGTTATTCCACTAATAATATTATCCCTAGGGGGCCTACCCCCGCTCAC
Callithrix         ATGAGTAATACCCATAATCCCACTAATAATAATATCATTAGGGGGCCTACCCCCACTAAC
Alouatta           ATGAGTAATACCCATAATTCCATTAATAATGATGTCCCTAGGAGGCTTACCCCCACTAAC
                   ****   *****  * ** *** *******  * **  **** *** ******* ** **

Plecturocebus      AGGCTTCTCCCCCAAATGAGTTATTATACAAGAATTTACAAACAATAATAGCCTTATCAT
Callithrix         AGGTTTCTCCCCTAAATGAGCCATTATACAAGAACTTACAAAAAACAACAGCCTAATTAT
Alouatta           AGGCTTTTCCCCTAAATGAGCAATCATACAAGAACTTACAAAAAATGACAACCTTATTAT
                   *** ** ***** *******  ** ********* ******* **  * * *** ** **

Plecturocebus      CCCTCTCACCATGGCCATACTCACACTAGTGAACTTATATTTTTACTTACGCCTAACATA
Callithrix         CCCACTCACAATAGCCATATTAACACTAATAAACCTCTACTTCTATATACGCCTAACATA
Alouatta           TCCCCTCACTATAGCCATACTTACACTAATAAACTTATACTTCTATATACGCCTAACATA
                    ** ***** ** ****** * ****** * *** * ** ** **  *************

Plecturocebus      CTCTATCTCAGTAACAATATTTCCTACATCCAACAACGCAAAAATTAACTGACAACTAAA
Callithrix         TTCCATCTCAATAACAATATTCCCTACATCAAACAACACAAAAATTAACTGACAACTAAA
Alouatta           CTCCATCTCAATAACAATATTCCCCACATCTAACAACACAAAAATTAACTGACAACTAAA
                    ** ****** ********** ** ***** ****** **********************

Plecturocebus      ATGTACAAAACTAACCCCCCTCCTCACTCCACTTATAATCTCCTCCACCCTCCTTCTACC
Callithrix         ATACACAAAACCAGTACCACTCCTACCCCCACTCATAACCCTTTCCACATTAATACTACC
Alouatta           ACACATTAAACTCTCCCCACTTCTCCCCCCACTCATAATTTCTTCCACCCTTCTATTACC
                   *   *  ****     ** ** **  * ***** ****     *****  *  *  ****

Plecturocebus      CTTAACACCACTAATATTAATAACCTAGAAATTTAGGTTAATAAGACCAAGAGCCTTCAA
Callithrix         TCTAACCCCACTAATACTTACAAACTAGAAATTTAGGTTAATAAGACCAAGAGCCTTCAA
Alouatta           CACAACCCCGCTAATACTAATAATCTAGAAATTTAGGTTAACAAGACCAAGAGCCTTCAA
                      *** ** ****** * * ** ***************** ******************

Plecturocebus      AGCCCTCAGTAAGTATAATTTACTTAATTTCTGCTACGCCCTAAGGACTGCAAAACTCTA
Callithrix         AGCCCTTAGTAAGTAAACACTACTTAATTTCTGCACCACTATAAGGACTGCAAAACTTTA
Alouatta           AGCTCTAAGCAAGTA-ATTTTACTTAATTTCTGCACCACCATAAGGACTGCAAAACTCCA
                   *** ** ** ***** *   **************  * *  ****************  *

Plecturocebus      TATTACATCTACTGAACGCAAATCAGTTGCTTTTATTAAGCTAAGCCCTTCCTAGACTGA
Callithrix         TTCTGCATCAACTGAACGCAAATCAATTACTTTAATTAAGCTAAGCCCTTCCTAGATTGA
Alouatta           CTTTGCATCAACTGAACGCAAATCAATTACTTTTATTAAGCTAAGCCCTTCCTAGACTGA
                      * **** *************** ** **** ********************** ***

Plecturocebus      TGGGACTCTAACCCACAAAAATTTAGTTAACAGCTAAATAACCTAATCAACTGGCTTCAA
Callithrix         TGGGACTCTAACCCACAAAAATTTAGTTAACAGCTAAATAACCTAATCAACTGGCTTCAA
Alouatta           TGGGACTCTAACCCACAAAAATTTAGTTAACAGCTAAATAACCTAATCAACTGGCTTCAA
                   ************************************************************

Plecturocebus      TCTACTTCTCCCGCCGTTGGGGGAAAAAAGGCGGGAGAAGCCCCGGCAGAATTGAAGCTG
Callithrix         TCTACTTCTCCCGCCGTC-AGGCAAAAAAGGCGGGAGAAGCCCCGGCAGGGTTGAAGCTG
Alouatta           TCTACTTCTCCCGCCGTT-AGGAAAAAAAGGCGGGAGAAGCCCCGGCAGAATTGAAGCTG
                   *****************   ** **************************  *********

Plecturocebus      CTTCTCTGAATTTGCAATTCAATGTGATATATCACCTCAGGGCTGGTAAAAAGAGGACTT
Callithrix         CTTCTTTGAATTTGCAATTCAATATGATATATCACCTCGGAGCTGGTAAAAAGAGGGGTT
Alouatta           CTTCTTTGAATTTGCAATTCAATATGATAAATCACCTCAGAGCTGGCAAAAAGAGGATTT
                   ***** ***************** ***** ******** * ***** *********  **

Plecturocebus      A--CCCCTGTCTTTAGATTTACAGTCTAATGCTTACTCAGCCATTTTACCTTCCTCCTAC
Callithrix         ACTCCTCTGTCTTTAGATTTACAGTCTAATGCTTACTCAGCCATTTTACC-----CCTAA
Alouatta           C--CCTCTGTCTTTAGATTTACAGTCTAATGCTTACTCAGCCATTTTACCCT-CTCTTAC
                      ** ********************************************     * ** 

Plecturocebus      CTATGTTCATAAATCGCTGACTATTTTCAACCAATCATAAAGACATCGGAACACTTTATC
Callithrix         CTATGTTCATAAATCGATGATTATTTTCAACCAACCACAAAGACATCGGAACCCTATATT
Alouatta           TTATGTTCATAAACCGCTGATTATTTTCAACTAACCATAAAGACATCGGAACACTATATT
                    ************ ** *** ********** ** ** ************** ** *** 

Plecturocebus      TTCTATTTGGGGCCTGAGCAGGAGCAGTCGGAACTGCCCTAAGCCTTTTAATTCGAGCCG
Callithrix         TACTATTCGGTGCATGAGCAGGAGCAGTGGGGACAGCCCTAAGCCTCCTAATCCGAGCAG
Alouatta           TACTATTTGGCGCATGAGCAGGGGCAGTAGGAACAGCCCTAAGCCTCCTAATTCGAGCAG
                   * ***** ** ** ******** ***** ** ** ***********  **** ***** *

Plecturocebus      AGTTAGGACAACCTGGAAGTTTAATAGAAGATGATCACGTCTACAACGTTATTGTTACCT
Callithrix         AACTAGGCCAACCAGGAAGCCTGATAGAAGATGATCATGTCTACAATGTAATCGTCACAT
Alouatta           AGCTCGGTCAGCCTGGAAGTTTAATAGAAGACGACCATGTTTATAACGTTATCGTCACCT
                   *  * ** ** ** *****  * ******** ** ** ** ** ** ** ** ** ** *

Plecturocebus      CTCACGCATTTATTATAATCTTTTTTATAGTTATACCAATTATAATTGGGGGCTTTGGAA
Callithrix         CTCACGCATTTATTATAATTTTCTTCATGGTAATGCCAATCATAATTGGGGGCTTCGGAA
Alouatta           CCCACGCATTCATTATAATTTTCTTCATAGTAATGCCAATTATAATTGGGGGCTTTGGAA
                   * ******** ******** ** ** ** ** ** ***** ************** ****

Plecturocebus      ACTGACTTGTGCCCCTTATAATTGGTGCGCCGGATATAGCATTCCCCCGAATAAATAATA
Callithrix         ACTGACTTGTCCCCTTAATAATTGGCGCCCCAGACATAGCATTCCCCCGAATAAATAACA
Alouatta           ACTGACTTGTCCCCCTAATAATTGGTGCCCCCGATATAGCATTTCCCCGAATAAATAATA
                   ********** *** * ******** ** ** ** ******** ************** *

Plecturocebus      TAAGCTTCTGACTCCTCCCTCCGTCACTCCTCCTATTACTTGCGTCTTCAACTCTAGAGG
Callithrix         TGAGCTTTTGACTCCTGCCCCCCTCACTACTTCTCCTACTAGCATCCTCTACCCTCGAAG
Alouatta           TAAGCTTCTGACTTCTACCCCCATCCCTTCTTCTATTACTCGCATCCTCAACCCTAGAAG
                   * ***** ***** ** ** ** ** ** ** **  **** ** ** ** ** ** ** *

Plecturocebus      CCGGCGCAGGGACTGGCTGAACAGTATATCCACCCCTAGCCGGAAATATGTCTCATCCAG
Callithrix         CCGGTGCCGGGACTGGTTGAACAGTCTACCCGCCCTTAGCAGGTAACATATCACACCCAG
Alouatta           CCGGAGCCGGTACTGGTTGAACAGTTTACCCACCTCTAGCGGGAAATATGTCACACCCAG
                   **** ** ** ***** ******** ** ** **  **** ** ** ** ** ** ****

Plecturocebus      GAGCCTCAGTAGACTTAACTATTTTCTCGCTACACCTGGCAGGTGTATCCTCCATCCTGG
Callithrix         GAGCTTCTGTAGACCTAACCATTTTTTCATTGCATTTAGCAGGTGTATCTTCCATTCTAG
Alouatta           GAGCCTCTGTAGACCTCACTATTTTTTCACTTCACCTGGCTGGTATTTCCTCCATTCTAG
                   **** ** ****** * ** ***** **  * **  * ** *** * ** ***** ** *

Plecturocebus      GAGCTATTAATTTTATTACTACAATTATTAATATAAAACCCCCAGCCATAACCCAGTACC
Callithrix         GGGCTATCAACTTTATTACAACAATTATTAACATAAAACCTCCAGCCATGACCCAATACC
Alouatta           GGGCTATTAATTTTATCACAACAATTATTAACATAAAACCCCCAGCCATAACCCAATATC
                   * ***** ** ***** ** *********** ******** ******** ***** ** *

Plecturocebus      AAACCCCTCTTTTTGTATGATCAGTTCTTATTACAGCAGTTCTTCTCCTCCTATCTCTCC
Callithrix         AAACTCCCCTATTCGTATGATCTGTACTAATTACAGCAGTCCTCCTTCTACTCTCCCTTC
Alouatta           AGACACCTTTATTTGTCTGATCTGTCCTTATTACAGCAGTCTTACTACTTCTGTCTCTTC
                   * ** **  * ** ** ***** ** ** ***********  * ** ** ** ** ** *

Plecturocebus      CTGTCCTAGCTGCTGGAATTACTATACTATTAACAGACCGTAATCTTAACACCACTTTCT
Callithrix         CAGTTTTAGCTGCCGGAATCACTATACTATTAACTGACCGCAACCTCAATACCACCTTCT
Alouatta           CAGTTCTGGCTGCTGGAATCACCATACTATTAACAGACCGCAACCTTAATACTACATTCT
                   * **  * ***** ***** ** *********** ***** ** ** ** ** ** ****

Plecturocebus      TTGACCCAGCCGGTGGGGGTGACCCAATCCTATATCAACACCTATTTTGATTCTTTGGTC
Callithrix         TCGACCCCGCTGGTGGTGGAGACCCAGTTCTATATCAACACCTGTTCTGATTTTTCGGCC
Alouatta           TCGATCCTGCAGGTGGTGGAGACCCTATCCTATATCAACACCTGTTCTGATTTTTTGGGC
                   * ** ** ** ***** ** *****  * ************** ** ***** ** ** *

Plecturocebus      ATCCTGAAGTGTATATTCTTATTTTACCCGGCTTCGGAATAATCTCTCACATCGTAACAT
Callithrix         ACCCTGAAGTATATATTCTCATTCTCCCAGGTTTCGGAATAATCTCGCACATTGTAACGT
Alouatta           ACCCTGAAGTGTACATCCTTATTCTTCCAGGCTTCGGAATAATCTCACATATTGTAACAT
                   * ******** ** ** ** *** * ** ** ************** ** ** ***** *

Plecturocebus      ATTACTCCAACAAAAAAGAACCATTTGGATATATAGGAATAGTATGAGCTATAATATCCA
Callithrix         ACTATTCAAATAAAAAAGAGCCATTTGGCTATATGGGCATGGTCTGAGCTATAATATCTA
Alouatta           ATTATTCTAATAAAAAAGAACCATTTGGATATATAGGAATAGTATGAGCCATAATATCTA
                   * ** ** ** ******** ******** ***** ** ** ** ***** ******** *

Plecturocebus      TCGGTTTCTTAGGATTTATTGTATGAGCACATCACATATTTACAGTAGGAATAGATGTAG
Callithrix         TTGGCTTCCTAGGATTTATTGTATGAGCCCACCATATATTCACAGTAGGAATAGATGTAG
Alouatta           TTGGTTTCCTAGGATTTATTGTATGAGCTCACCACATATTCACTGTAGGCATAGACGTAG
                   * ** *** ******************* ** ** ***** ** ***** ***** ****

Plecturocebus      ATACCCGTGCATATTTTACATCAGCTACTATAATTATTGCCATCCCCACCGGAGTAAAAG
Callithrix         ACACTCGCGCATATTTCACATCAGCCACTATAATCATCGCAATCCCCACCGGGGTAAAAG
Alouatta           ATACACGTGCATACTTCACATCAGCCACCATAATCATCGCCATTCCCACAGGAGTAAAAG
                   * ** ** ***** ** ******** ** ***** ** ** ** ***** ** *******

Plecturocebus      TCTTCAGCTGACTGGCCACACTACATGGCGGCAACATTAAATGATCTCCTGCAATACTAT
Callithrix         TATTTAGCTGATTGGCCACACTACACGGCGGTAATATTAAATGATCCCCTGCAATATTAT
Alouatta           TATTTAGTTGATTAGCCACACTGCACGGCGGTAATATCAAATGATCTCCCGCAATACTAT
                   * ** ** *** * ******** ** ***** ** ** ******** ** ****** ***

Plecturocebus      GAGCCCTAGGCTTCATTTTCCTTTTTACTGTAGGCGGACTGACCGGGATTGTACTAGCCA
Callithrix         GGGCCCTGGGCTTTATCTTTCTTTTCACCGTGGGTGGGTTAACAGGGATCGTACTAGCTA
Alouatta           GAGCTCTGGGCTTTATTTTCCTTTTTACCGTAGGTGGACTAACAGGAATTGTATTAGCCA
                   * ** ** ***** ** ** ***** ** ** ** **  * ** ** ** *** **** *

Plecturocebus      ACTCATCACTAGATATTGTTTTACACGATACATACTATGTAGTAGCCCACTTTCACTATG
Callithrix         ACTCATCATTAGACATTGTATTACACGACACATACTATGTAGTAGCACACTTCCACTATG
Alouatta           ACTCATCATTAGATATCGTCCTACATGACACATATTATGTGGTAGCCCACTTTCATTATG
                   ******** **** ** **  **** ** ***** ***** ***** ***** ** ****

Plecturocebus      TACTATCCATAGGGGCAGTATTTGCTATTATAGGAGGCTTTATTCACTGATTCCCACTAT
Callithrix         TACTATCTATGGGGGCAGTGTTTGCTATTATGGGGGGCTTTATCCACTGATTTCCACTAT
Alouatta           TTTTATCTATAGGAGCAGTATTCGCCATCATAGGAGGCTTCATTCACTGATTCCCACTAT
                   *  **** ** ** ***** ** ** ** ** ** ***** ** ******** *******

Plecturocebus      TCTCTGGCTATACCCTTGATCAAACTTATGCTAAAATTCACTTCAGTATTATATTTGTAG
Callithrix         TTTCAGGCTATACACTTGACCAAACCTATGCTAAAGTTCATTTTACTATCATATTTGTAG
Alouatta           TCTCTGGTTACACGCTCGACCAGACCTATGCTAAAATTCACTTTACCATTATATTTGTGG
                   * ** ** ** ** ** ** ** ** ********* **** ** *  ** ******** *

Plecturocebus      GTGTAAACATAACCTTCTTTCCCCAACACTTTCTTGGTCTATCCGGCATGCCTCGACGTT
Callithrix         GCGTAAATTTAACCTTCTTTCCACAGCACTTCCTTGGCCTATCCGGAATGCCCCGACGAT
Alouatta           GCGTAAATCTAACCTTTTTCCCACAACACTTTCTCGGCTTATCTGGAATACCCCGACGAT
                   * *****  ******* ** ** ** ***** ** **  **** ** ** ** ***** *

Plecturocebus      ACTCTGATTATCCTGATGCCTACACAACATGAAATATCGTATCATCCGTAGGTTCATTTA
Callithrix         ACTCAGATTACCCAGATGCATACACAACATGAAACATCGTATCATCCGTAGGGTCCTTCA
Alouatta           ATTCAGATTACCCCGATGCATATACTACATGAAATATCGTATCATCTGTAGGCTCATTTA
                   * ** ***** ** ***** ** ** ******** *********** ***** ** ** *

Plecturocebus      TTTCACTAACAGCAGTTATCCTGATAATCTTTATGATCTGAGAGGCTTTCTCCTCAAAAC
Callithrix         TCTCATTAACAGCAGTTATTCTTATAATTTTCATGATTTGAGAGGCATTCTCCTCAAAAC
Alouatta           TTTCATTAACAGCAGTTATCCTTATAATTTTTATAATTTGAGAAGCATTTTCCTCAAAAC
                   * *** ************* ** ***** ** ** ** ***** ** ** **********

Plecturocebus      GGAAAGTCATAACTGTTGAACAACTATCCTCCAACCTCGAGTGGCTTTACGGCTGCCCTC
Callithrix         GAAAAGTCTCTGCCATCGAACAACTATCCACAAACCTAGAGTGACTACATGGCTGCCCTC
Alouatta           GAAAAGTCTCAACCGTCGAACAACTAACTACCAACCTAGAATGACTTTATGGCTGCCCCC
                   * ******    *  * ********* *  * ***** ** ** **  * ******** *

Plecturocebus      CTCCCTATCACACATTTGAAGAAGCTACTTATGTAAAAATTCTCAACGAAAAAGGAAGGA
Callithrix         CACCCTACCACACATTTGAAGAAGTCACCTATGTAAAAACCTTGAGCGAAAAAGGAAGGA
Alouatta           CTCCTTATCACACATTTGAAGAATCTACCTATGTAAAATCTTTAAGCGAAAAAGGAAGGA
                   * ** ** ***************   ** *********    * * **************

Plecturocebus      TTTGAACCCCCAAAAATTGGTTTCAAGCCAACTCCATAGACCCTATGACTTTTTCAATAA
Callithrix         TTTGAACCCCCAAAAATTGGTTTCAAGCCAATCCCATAGACCCTATGACTTTTTCAATAA
Alouatta           TTTGAACCCCCAAAAATTGGTTTCAAGCCAATCCCATAGACCCTATGACTTTTTCAATGA
                   *******************************  ************************* *

Plecturocebus      GATATTAGTAAAATAATTACATAACTTTGTCAAAGTTAAGTTATAGACTAATC-CCTATA
Callithrix         GGTATTAGTAAAGTAATTACGTAACTTTGTCAAAGTTAAATCATAGACTAAACATCTATA
Alouatta           GATATTAGTAAAAAAATTACATAACTTTGTCAAAGTTAAATTATAGACCAAAC-CCTATA
                   * **********  ****** ****************** * ****** ** *  *****

Plecturocebus      TATCTTACATGGCCCACCCAGCCCAACTAGGCCTACAAAATGCAGCATCCCCTATTATAG
Callithrix         TATCTTA-ATGGCAGCACCAGCCCAACTAGGCCTACAAAACGCCGCATCCCCAATCATAG
Alouatta           TATCTTA-ATGGCACACCCAGCCCAACTAGGCCTACAAAACGCTACATCCCCTATCATAG
                   ******* *****    *********************** **  ******* ** ****

Plecturocebus      AAGAACTCATTGCCTTCCATGACCATGCCCTGATAATTATCTTTCTTATTAGCTCTCTGG
Callithrix         AAGAACTTATTGCCTTCCATGACCATGCTCTAATAATCATTTTCTTAATTAGCTCACTAG
Alouatta           AAGAACTCATTGCCTTTCACGATCATGCTCTAATAATTATTTTTCTAATTAGTTCACTAG
                   ******* ******** ** ** ***** ** ***** ** **  * ***** ** ** *

Plecturocebus      TTCTGTATATCATCTCCTTAATACTTACTACAAAACTAACACATACCAGCACAATAAATG
Callithrix         TTCTATATATCATTTCTCTAATACTTACTACAAAACTGACACACACCAGTACCATAAACG
Alouatta           TACTATATGTTATTTCCCTAATGCTCACAACTAAACTAACCCACACCAGCACAATAAACG
                   * ** *** * ** **  **** ** ** ** ***** ** ** ***** ** ***** *

Plecturocebus      CCCAAGAAATTGAAATTATCTGAACCATTCTACCTGCCATTATCCTTATTATAATTGCCC
Callithrix         CTCAAGAAATCGAAATAATCTGAACCATCCTACCTGCAATAATCCTCATTATAATTGCCC
Alouatta           CCCAAGAAATCGAAATAATTTGAACCATTCTACCTGCAATTATCCTTATCATAATTGCTC
                   * ******** ***** ** ******** ******** ** ***** ** ******** *

Plecturocebus      TTCCATCCTTACGTATCCTGTACATAACAGACGAATTTAATAAACCATACTTAACCCTTA
Callithrix         TTCCATCCCTACGTATTTTATATATAACAGACGAGTTTAATAAACCATACCTTACTCTTA
Alouatta           TCCCATCCCTACGCATCTTATACATAACAGACGAATTTAATAAGCCCTACTTAACTCTTA
                   * ****** **** **  * ** *********** ******** ** *** * ** ****

Plecturocebus      AAGCTATTGGTCACCAGTGATACTGAAGCTATGAATATTCAGACTACGAAGACCTAGCCT
Callithrix         AAGCAATTGGCCACCAATGATACTGAAGCTACGAATACTCCGACTATGAAGACTTAGCAT
Alouatta           AAGCCATTGGCCACCAATGATACTGAAGTTATGAGTACTCAGACTATGAAGACTTAGCCT
                   **** ***** ***** *********** ** ** ** ** ***** ****** **** *

Plecturocebus      TTGATTCCTATATTATGCCCACATATTTTCTTGAGCCTGGCGAATTCCGACTTCTTGAAG
Callithrix         TCGACTCTTATATTATACCAACATATTTCCTTGAGCCCGGGGAATTCCGGCTCCTTGAAG
Alouatta           TCGACTCCTACATCACACCTACATACTTTCTTGAACCTGGAGAATTCCGACTCCTTGAAG
                   * ** ** ** ** *  ** ***** ** ***** ** ** ******** ** *******

Plecturocebus      TAGACAACCGCACCACCCTCCCAATAGAAGCAGATATCCGCATACTAATTTCATCACAAG
Callithrix         TAGACAACCGAACAACCTTGCCTATAGAAGCTGATATCCGTATATTAATCTCATCACAGG
Alouatta           TAGACAACCGAACAACTCTACCCATAGAAGCAGACATCCGTATACTAATCTCATCACAAG
                   ********** ** **  * ** ******** ** ***** *** **** ******** *

Plecturocebus      ACGTACTACACTCATGAGCTGTACCATCATTAGGCGTTAAAGCAGATGCAATCCCTGGAC
Callithrix         ATGTTTTACACTCATGAGCTGTGCCCTCACTAGGCGTGAAAACAGATGCAATCCCCGGAC
Alouatta           ACGTCTTGCACTCATGAGCCGTTCCATCACTAGGCATTAAGGCAGATGCAATCCCTGGAC
                   * **  * *********** ** ** *** ***** * **  ************* ****

Plecturocebus      GCTTAAATCAAGCTATAGTAGCCTCAATACGACCAGGCCTTTTCTACGGACAGTGCTCAG
Callithrix         GCTTAAACCAAGCCATAGTAGCTTCCATACGACCAGGCCTATACTACGGGCAATGCTCAG
Alouatta           GCTTAAACCAAGCTATACTGGCCTCCATACGACCAGGCCTATTTTATGGCCAGTGCTCAG
                   ******* ***** *** * ** ** ************** *  ** ** ** *******

Plecturocebus      AAATTTGTGGATCAAATCATAGCTTTATACCTATTGTTCTAGAATTTATCTACTTCCAAG
Callithrix         AAATTTGTGGATCCAACCACAGCTTTATGCCCATTGTACTAGAATTTATTTACTTCCAAG
Alouatta           AAATCTGCGGGTCAAATCATAGCTTTATACCCATTGTCCTAGAATTTATTTACTTCCAAG
                   **** ** ** ** ** ** ******** ** ***** *********** **********

Plecturocebus      ACTTTGAAGTCTGAGCCTCCTACCTGTACATTGTATCGCTATAAAGCTAGTAAGCATTAA
Callithrix         ATTTCGAAGTATGAGCCTCATACCTATACATTGTATCACTGTAAAGCTAACCAGCATTAA
Alouatta           ACTTCGAAGTATGAGCCTCATACCTATACATCGTATCACTGTAAAGCTACCTAGCATTAA
                   * ** ***** ******** ***** ***** ***** ** ********   ********

Plecturocebus      CCTTTTAAGTTAAAGACTGGGA--ATATTAATCCCTATAGCGAATTCCCCAACTAGATAT
Callithrix         CCTTTTAAGTTAAAGATTGAGAGGACCTCCCTCTCTACAGTGAGTGCCCCAACTAAACAT
Alouatta           CCTTTTAAGTTAAAGATTGAGA--ACACCCCTCTCTACAGTGAATGCCTCAACTGGATAT
                   **************** ** **  *      ** *** ** ** * ** *****  * **

Plecturocebus      CTCGCCATGACCATTGGTAATTATATCAATAGTTGTGGCCCTATTTTACACTATCCAATT
Callithrix         CTCACCATGACCAATGGTGATTTTATCGATAATCGTCACCTTATTCTACATCATCCAATT
Alouatta           ATCACCGTGACCAATAGTAATTATATCAATAATTTTAACCCTATTTTACATTACTCAATT
                    ** ** ****** * ** *** **** *** *  *  ** **** ****  *  *****

Plecturocebus      AAAAGTATTAAACTTCACCTTCTACGCCTCTCCAGTGTCAAAATTAATTAAAATACAAAA
Callithrix         GAAGCTATTAAATTTTACTTTCTATACTACCCCCTCACCAAAATCAACTAAAACACAAAA
Alouatta           AAAAATACTGAACTTTACTTTTCACACCACCCCATCATCAAAATTAACGATATCACATAA
                    **  ** * ** ** ** **  *  *  * **     ****** **  * *  *** **

Plecturocebus      ACATAATGCAACCTGAGAACTAAAATGAACCAAAATCTATTTGCCTCATTCAATATCCCA
Callithrix         ACATAAATCAACTTGAGAACTAAAATGAACCAAAATCTATTCGCTTCCTTCGACATCCCA
Alouatta           ACACAAAACAACCTGAGAACTAAAATGAACCAAAATTTATTTGCCTCCTTCAACGTACCA
                   *** **  **** *********************** **** ** ** *** *  * ***

Plecturocebus      ACAATTCTAGGAATCCCCCTAATCACATTAATTATTTTATTTCCCACCCTGCTAATAACA
Callithrix         GCAATCCTAGGTATCCCCCTAGTGATTCTGATCATCATGCTTCCTGCCACATTTATTACA
Alouatta           ATAATACTAGGAATCCCCCTAGTTACACTAATTATTCTATTTCCCACCATGTTAATTTCA
                     *** ***** ********* * *   * ** **  *  ****  **    * **  **

Plecturocebus      CCTCCCAATAAATTAATCAGCAACCGAATTTCTCTACTTCAACAATGATTAATTCAACTT
Callithrix         CCCACTAATAACCTAATTAACAACCGATTCTCCTCTCTCCAACAATGACTAATTCAGCTC
Alouatta           TCCCCTAATAAACTAATCAACAATCGACTCTCCTCTATTCAACAATGACTAGTCCAACTT
                    *  * *****  **** * *** *** * **     * ********* ** * ** ** 

Plecturocebus      ACACTAAAACAACTAATACTAAATCATAGCACTAAGGGACGAACTTGATCCCTAATACTT
Callithrix         ATATTAAAACAAATGATAATTACCCATACTACCAAAGGACGAACTTGATCCCTCATGCTT
Alouatta           ACACTAAAACAAATAATAACAACCCATAGCATTAAAGGGCGAACTTGATCCCTTATACTC
                   * * ******** * ***   *  ****  *  ** ** ************** ** ** 

Plecturocebus      CTAACCCTGATCACTTTTATTGCTCTTAACAACCTCCTTGGACTTACACCTTACGCATTT
Callithrix         ATAGCCCTAGTCACTTTTATCGCTTTAAACAACCTCCTCGGACTTACACCATACGCATTT
Alouatta           ATAGCCCTAATCACTTTCATCGCCCTAAACAATCTCCTCGGAATAACACCATACGCATTC
                    ** ****  ******* ** **  * ***** ***** *** * ***** ******** 

Plecturocebus      ACACCAACCACCCAGCTATCTATGAATATTGGAATAGCAATCCCCCTATGAGCGGCCACA
Callithrix         ACACCAACCACCCAACTATCAATAAATCTAGGCATGGCAATCCCCCTATGAGCAGCAACT
Alouatta           ACACCAACCACCCAGCTATCAATAAACTTAGCTATAGCAATCCCTCTATGAGCGGCCACC
                   ************** ***** ** **  * *  ** ******** ******** ** ** 

Plecturocebus      GTACTTATAGGATTTCGATTCAAAACAAAAGCATCTTTAGCCCACTTTTTACCCCAAGGA
Callithrix         GTGCTCATAGGGTTGCGATTTAAAACAAAACTAGCTCTCGCCCACTTCCTACCGCAAGGA
Alouatta           GTACTTATAGGACTTCGATTTAAAACAAAAGCATCTCTTGCCCATTTTTTACCCCAAGGA
                   ** ** *****  * ***** *********  * ** * ***** **  **** ******

Plecturocebus      ACCCCTATTCCTCTTATTCCCATACTAGTAATTATTGAAACAATTAGCCTCTTCATTCAA
Callithrix         ACACCCGCACCACTCATCCCTATACTAATCATTATCGAAACAATTAGCCTCTTCATCCAA
Alouatta           ACACCTATGCCACTTATCCCTATACTAGTTGTCATTGAAACAATCAGCCTCTTTATTCAA
                   ** **    ** ** ** ** ****** *  * ** ******** ******** ** ***

Plecturocebus      CCAATAGCACTAGCCGTACGTTTAACAGCTAATATCACAGCAGGACATCTCCTAATGCAT
Callithrix         CCAGTAGCCCTAGCTGTACGACTTACAGCTAATATCACAGCAGGTCACCTGTTAATGCAC
Alouatta           CCAATCGCACTAGCCGTACGACTAACAGCCAATATCACAGCAGGCCATCTGTTAATACAC
                   *** * ** ***** *****  * ***** ************** ** **  **** ** 

Plecturocebus      CTACTTGGAGACACCGCACTAACTCTAATATCTATTTATTTCTCTTCATCTATAATTACT
Callithrix         CTACTTGGTGACACTACATTAACTCTCATGTCCATCTACCTATCTTCCTCTACAATTACC
Alouatta           TTACTTGGGGATACCACGCTAACCCTTCTATCCTCTTACATCTCCTCTTCCATAATCACA
                    ******* ** **  *  **** **  * **    **  * ** ** ** * *** ** 

Plecturocebus      GTTATCGTAATTATCCTTCTAATTACCCTAGAATTAGGTGTAGCCTTAATTCAAGCCTAC
Callithrix         ATTATCATTATTATCTTACTCATTACCTTAGAACTAGGTGTTGCACTCATCCAAGCATAT
Alouatta           TTTGTTATCGTTATTTTACTTATTATACTAGAACTAGGTGTAGCCCTAATCCAAGCCTAC
                    ** *  *  ****  * ** ****   ***** ******* **  * ** ***** ** 

Plecturocebus      GTCTTTACACTTCTAGTAAGCCTTTACCTACATGATAACTCTTAATGACCCACCAAGCTC
Callithrix         GTATTCACCCTCTTAGTAAGCCTATATCTACATGACAACTCATAATGACACACCAGACAC
Alouatta           GTCTTTACACTCTTAGTAAGCCTTTACCTACACGATAACTCATAATGACTCACCAAACAC
                   ** ** ** **  ********** ** ***** ** ***** ******* *****  * *

Plecturocebus      ATGCCTTCCACATAGTTAACCCAAGCCCCTGACCATTAACAGGAGCTCTGTCCGCCTTCC
Callithrix         ATGCCTACCACATAGTTAACCCAAGCCCTTGACCACTTACAGGAGCCCTATCAGCATTCT
Alouatta           ACGCTTACCACATAGTTAACCCAAGCCCCTGACCATTAACAGGAGCCCTATCTGCTTTCC
                   * ** * ********************* ****** * ******** ** ** ** *** 

Plecturocebus      TACTTACCTCAGGCTTAATTATATGATTCCACTTTTATCACAGCCTTCTCCTCATAGCAG
Callithrix         TACTTACATCTGGCATAATTATATGGTTCCATTTCTATCACACTTCCCTCCTCACTGCAG
Alouatta           TATTAACTTCTGGCCTAGCCATATGATTTCACTTCTATTACATCCCCCTTCTTACCATAG
                   ** * ** ** *** **   ***** ** ** ** *** ***     ** ** *    **

Plecturocebus      GTCTACTGGCCAGCACAATAACTATATTTCAATGATGACGGGATGTCGTCCGAGAAGGAA
Callithrix         GGCTACTAGCTAGCACAATAACAATATTTCAATGATGACGAGACATTGTACGAGAGGGCA
Alouatta           GATTACTAGCCAGCGCATTAACAATATTTCAATGATGACGAGATGTGGTACGAGAGGCTA
                   *  **** ** *** ** **** ***************** **  * ** ***** *  *

Plecturocebus      CATATCAAGGACATCACACCACCCCCGTCCAAAAGGGCCTTCGATACGGAATAGTCCTAT
Callithrix         CATATCAAGGCCACCACACCTCTCCTGTACAAAAAGGCCTTCGATACGGCATAATCCTTT
Alouatta           CATACCAAGGCCACCATACCCTGCCTGTCCAAAAAGGCCTCCGATACGGGATAGTTCTAT
                   **** ***** ** ** ***   ** ** ***** ***** ******** *** * ** *

Plecturocebus      TTATTATTTCAGAAGTTTTTTTCTTTGCCGGCTTCTTCTGAGCATTCTACCACTCTAGCT
Callithrix         TTATTATCTCAGAAGTATTTTTCTTCGCTGGCTTCTTCTGAGCATTCTATCACTCCAGCT
Alouatta           TTATTATCTCAGAAATCTTCTTCTTTGCTGGCTTCTTTTGAGCATTTTATCACTCCAGCC
                   ******* ****** * ** ***** ** ******** ******** ** ***** *** 

Plecturocebus      TAGCCCCAACCCCACAAACAGGAGGACACTGGCCCCCAACAGGCATCTTTCCTCTTAATC
Callithrix         TAGCCCCAACCCCACAAACAGGGGGGCACTGACCCCCTACAGGAATTTTTCCTCTTAACC
Alouatta           TAGCCCCAACCCCACAAACAGGAGGACATTGACCCCCAACAGGTATTTTCCCCCTTAACC
                   ********************** ** ** ** ***** ***** ** ** ** ***** *

Plecturocebus      CTATAGAAGTTCCCCTACTAAATACAGCAGTTCTACTTGCATCAGGAGTAACAATTACCT
Callithrix         CCATAGAAGTGCCACTACTAAACACAGCCGTACTATTAGCATCAGGAGTCACAATCACTT
Alouatta           CAATAGAAGTACCACTTCTAAATACAGCCATTCTATTAGCATCAGGAGTTACAATTACCT
                   * ******** ** ** ***** *****  * *** * *********** ***** ** *

Plecturocebus      GAGCTCACCATAGCCTAATAGAAGCTGACCAAGAAGAGTCAGCCCAAGCACTATTTATAA
Callithrix         GAGCGCACCATAGCCTAATAGAAGCCAATCGAAAAGAATCGGCCCAAGCTCTATCCATAA
Alouatta           GAGCACACCACAGCCTAATAGAAGCCAACCGAAAAGAATCAATTCAAGCACTAGCCCTAA
                   **** ***** **************  * * * **** **    ***** ***    ***

Plecturocebus      CTATTGCATTAGGTATCTACTTTACCTACCTACAAATATCAGAATATTCGGAAGCCCCCT
Callithrix         CCATTGCGCTAGGGGTCTACTTTACCTGCCTACAAATATCAGAATACTCTGAAACTTCAT
Alouatta           CCATTGCACTAGGAATTTACTTTACATGCTTACAATTATCAGAATACTCTGAAGCCTCCT
                   * *****  ****  * ******** * * ***** ********** ** *** *  * *

Plecturocebus      TCACCATCTCAGATGGAATTTATGGCTCCACATTCTTTATAGCAACAGGCTTTCACGGCC
Callithrix         TCACCATCTCAGACGGAATCTATGGGTCCACTTTCTTCATAGCTACGGGCTTCCATGGCC
Alouatta           TCACCATCTCTGACGGAATCTACGGATCAACATTCTTTGTAGCTACAGGCTTTCACGGTC
                   ********** ** ***** ** ** ** ** *****  **** ** ***** ** ** *

Plecturocebus      TACACGTCATCATCGGAACCACATTCCTCATTACATGCTACCTTCGCTTGCAAATAGATC
Callithrix         TACACGTCATCATCGGAACTACATTCCTTACTACCTGCTACTTCCGCCAACAACTATATC
Alouatta           TCCACGTCATTATTGGAACCACATTTCTCACAACCTGCTACGTCCGCCAACAACTATTTC
                   * ******** ** ***** ***** ** *  ** ****** * ***   *** **  **

Plecturocebus      ATTTTACATCCAATCACCACTTCGGCTTTGAAGCCGCCGCATGATATTGGCACTTCGTAG
Callithrix         ACTTCACATCTAGCCACCACTTCGGATTTGAAGCTGCTGCATGATACTGACACTTCGTAG
Alouatta           ATTTTACAACTAACCACCACTTTGGCTTCGAAGCCGCTGCATGATACTGACACTTCGTAG
                   * ** *** * *  ******** ** ** ***** ** ******** ** **********

Plecturocebus      ATGTAGTATGACTGTTCCTCTATATTTCTATTTATTGATGAGGATCTTACTCTCTTAGTA
Callithrix         ACGTAGTTTGACTATTCCTATACATCTCTATCTACTGATGAGGGTCTTACTCTCTTAGTA
Alouatta           ATGTGGTATGATTATTCCTATACATCTCTATCTATTGATGAGGGTCCTACTCTCTTAGTA
                   * ** ** *** * ***** ** ** ***** ** ******** ** *************

Plecturocebus      TAAGCAGTACAACCGACTTCCAATCAGTAGGCCTCAGCTAAACCTGAGAGAGAGTAATAA
Callithrix         TAAACAGTACTATTGACTTCCAATCAATAAGCCTC-GTATAACTCGAGAGGGAGTAATAA
Alouatta           TAAATAGTACTATTGACTTCCAATCAATAAGCCTT-GATAAACTCGAGAGAGAGTAATTA
                   ***  ***** *  ************ ** ****  *   ***  ***** ******* *

Plecturocebus      ATATAACACTAACCCTAATTACAAATATTATTCTAGCCCTTTTACTAATTACTATCACAT
Callithrix         ATCTGGCACTAGCCCTAATAACCTCCGTCCTCCTAGCCCTACTCCTAATCACCATAACAT
Alouatta           ATTTAACACTAACCCTAGCAACTAGTATTCTCCTAGCCTTATTACTAATTATTATCACAT
                   ** *  ***** *****   **     *  * ****** *  * ***** *  ** ****

Plecturocebus      TTTGAATTCCACAGCCCAATACCTACATAGAAAAACATAACCCCTACGAATGTGGGTTTG
Callithrix         TCTGACTCCCCCAACTAAATACATACACAGAAAAACACAACCCGTATGAATGTGGGTTTG
Alouatta           TTTGATTACCACAATTAAATACTTATACAGAAAAATTTAACCCCTATGAATGCGGATTCG
                   * *** * ** **    ***** ** * *******   ***** ** ***** ** ** *

Plecturocebus      ACCCCACAACATCTGCTCACCTACCTTTCTCCATAAAATTTTTCCTAGTAGCCATTACAT
Callithrix         ACCCCACAACCTCCGCCCACCTACCATTCTCCATAAAATTCTTCTTAATTGCTATTACAT
Alouatta           ATCCTACAACCTCAGCCCACCTGCCCTTCTCTATAAAATTTTTTCTAGTGGCCATCACAT
                   * ** ***** ** ** ***** ** ***** ******** **  ** * ** ** ****

Plecturocebus      TTCTCCTATTTGACCTAGAAATTGCCCTCCTCCTCCCCCTTCCATGGGCAACCCAAACAA
Callithrix         TCCTCCTATTTGACCTAGAAATCGCCTTACTTCTACCCCTGCCATGAGCAACCCAAACAA
Alouatta           TTCTCCTCTTTGACCTAGAAATTGCCCTACTATTACCCTTACCATGAGCAACCCAAACAA
                   * ***** ************** *** * **  * *** * ***** *************

Plecturocebus      ATAAATTAATACTAACAACTAATATAATTCTTGCCTTAATTATTATTTTAGTAGCAGGGC
Callithrix         ACAACTTAACATTAACTATTAACATGATTTTTACCCTTCTTATTATTCTAGCGCTGGGGT
Alouatta           ATAACCTAATATTAACAATTAATACAATCCTTACTTTAATTATTATTCTAGCACTAGGAT
                   * **  *** * **** * *** *  **  ** *  *  ******** ***     **  

Plecturocebus      TGGCCTACGAATGATCCCAAAAAGGACTAGATTGAGTTGAATTGATAAATAGTTTAATCA
Callithrix         TAGCCTACGAGTGATCTCAAAAGGGGTTGGATTGAGCTGAATTGGTAGATAGTTT-ATCT
Alouatta           TAGCCTATGAATGGACTCAAAAGGGGTTAGATTGAGTTGAATTGGTATATAGTTTAATC-
                   * ***** ** **  * ***** **  * ******* ******* ** ******* *** 

Plecturocebus      AAAACAAATGATTTCGACTCATTAGATTATGATAAATCATATTTATCAA---ATGCCCCT
Callithrix         AAAACAAATGATTTCGACTCATTAGATTATGAAAATTCATATTTACCAACACATGCCTTT
Alouatta           AAAACAAATGATTTCGACTCATTAGATTATGACAAGTCATATTTACCAA---ATGCCTTT
                   ******************************** ** ********* ***   *****  *

Plecturocebus      TATTTACATCAACACAATATTAGCATATTCCATATCCCTGCTAGGACTACTAATCTATCG
Callithrix         CATCTACACCAACGTCACACTAGCATATTTTATATCTCTGCTGGGACTATTGATCTACCG
Alouatta           CATCTATATCAACACCTCACTAGCATATTTCATATCTCTACTAGGACTATTAATCTACCG
                    ** ** * ****     * *********  ***** ** ** ****** * ***** **

Plecturocebus      ATCCCACCTAATATCATCCTTACTATGCCTAGAAGGCATAATATTATCACTATTTATTTT
Callithrix         GTCCCATCTAATATCATCCCTACTATGTTTGGAAGGCATAATACTATCACTATTCATTAT
Alouatta           ATCACATCTAATGTCATCCCTACTATGCTTGGAAGGTATAATATTATCACTATTCATTAT
                    ** ** ***** ****** *******  * ***** ****** ********** *** *

Plecturocebus      AATTACACTTACAACCCTAAATATACATATAACATTAATATTTATAATACCAATTACTCT
Callithrix         AACCACACTCACAACCCTAAACATACACACAATATTAATATATATAGTACCCATTACTCT
Alouatta           AGCCACACTCACAACCCTAAATATACATCTTATACTAATAAATATAATACCCATCACCCT
                   *   ***** *********** *****    * * *****  **** **** ** ** **

Plecturocebus      CCTAGTTTTCGCCGCATGTGAAGCCGCAGTCGGCCTAGCCCTGCTAATTCTTATCTCTAA
Callithrix         TCTAGTATTCGCCGCATGCGAAGCTGCAGTAGGCCTAGCCCTACTAATCTTAATCTCCAA
Alouatta           TCTAGTATTCGCCGCATGTGAGGCCGCAGTGGGACTAGCCCTACTAGTTCTAATTTCCAA
                    ***** *********** ** ** ***** ** ******** *** *  * ** ** **

Plecturocebus      TTTATATGGCCTAGACTATGTACAAAACCTAAACTTACTCCAATGCTAAAAATTATTTTA
Callithrix         CCTGTATGGCTTAGACTACGTACAAAACTTAAATCTACTCCAATGCTAAAAATTATTTTA
Alouatta           CCTATACGGCCTAGATTATGTACAAAACCTAAACCTACTTCAATGCTAAAAATTATTATA
                     * ** *** **** ** ********* ****  **** ***************** **

Plecturocebus      CCAACAATTATATTACTTCCAACAGTATGATTATCAAATAATCGTATAGTATGAATTAAT
Callithrix         CCAACAATCATAATACTACCAACTATATGATTATCAAAGCCCCATATAATATGAATTAAT
Alouatta           CCCACAATTATGCTTCTTCCAACAATATGACTTTCAAAAAACCGTATAATCTGAATCAAT
                   ** ***** **  * ** *****  ***** * *****    * **** * ***** ***

Plecturocebus      ACAATAACCTGAAGTCTACTAATCAGTGCTCTAGCCCTTGTGCCCCTATATTTACCAAAT
Callithrix         ACAATAACATGCAGCCTATTAATCAGTATTTTTACCCTTATAATACTATATATACCCAGC
Alouatta           ACAATAGCATGCAGCTTACTAATCAGCGCCCTAACCCCTTTACTCTTATATCTACCAAAC
                   ****** * ** **  ** *******     *  *** * *     ***** **** *  

Plecturocebus      ATATTATGCTACCTATCACTAATCTTCTTCTCAGATCCATTAACATCCCCACTCCTTGCC
Callithrix         AACTCATGCAATCTATCACTAACCTTCTTCTCCGACCCATTAACATCACCCCTACTGATA
Alouatta           AACCTATGCAACCTGTCATTAAATTTTTTCTCAGACCCATTAACATCTCCCCTCCTAACC
                   *    **** * ** *** ***  ** ***** ** *********** ** ** **    

Plecturocebus      CTAACAGCCTGGCTTCTACCCCTAATAATTCTAGCAACTCAACAACACCTCCATAACAAC
Callithrix         TTAACAGCCTGACTACTACCACTAATAATCCTAGCAACACAACAACACTTATACAACAAC
Alouatta           CTAACAGCCTGACTACTGCCCCTAATAGTTTTAGCAACCCAACAACATCTCCACAACAAC
                    ********** ** ** ** ****** *  ******* ********  *  * ******

Plecturocebus      CCCCTACCACGAAAAAAGCTTTATATATCAATACTAATTCTCCTACAAATTTCTTTAATC
Callithrix         CCCGCCCCACGAAAAAAATTATACATCTCAATACTAGTCTTTCTACAAATCTCCCTAATC
Alouatta           CCCTTTCCACGAAAAAAACTATATATCTCAATACTTATCCTCTTACAAATTTCTTTAATC
                   ***   ***********  * ** ** ********  *  *  ******* **  *****

Plecturocebus      ATAACATTTACAGCCACAGAACTTATCCTCTTCTATATTCTATTCGAGACCACTTTAATT
Callithrix         ATAACTTTCTCAGCCACCGAATTAGTCCTATTTTATATTTTATTTGAAACCACCCTAATC
Alouatta           ATAACATTCACAGCCTCAGAACTAATTTTGTTTTATATCCTATTCGAAACCACCCTAATC
                   ***** **  ***** * *** *  *  * ** *****  **** ** *****  **** 

Plecturocebus      CCCACCTTAATCGTTATCACCCGCTGAGGTTATCAGCCAGAACGCCTTAATGCAGGTTCA
Callithrix         CCCACCCTAATTATTATCACCCGCTGAGGGTACCAACCAGAACGTCTTAGTGCTGGCTCA
Alouatta           CCCACCCTAATTATCATTACTCGCTGAGGGTACCAACCAGAACGCCTCAATGCCGGCTCA
                   ****** ****  * ** ** ******** ** ** ******** ** * *** ** ***

Plecturocebus      TATTTTCTATTTTATACACTAGCCGGATCCCTCCCACTGCTTATTACACTCTTGTATTAC
Callithrix         TATTTCCTATTCTATACACTAGCCGGATCCCTCCCCCTACTAATCACACTCCTATACTAC
Alouatta           TATTTCTTATTCTACACACTAGCAGGATCTCTCCCACTACTCATCACACTCCTCTATTAC
                   *****  **** ** ******** ***** ***** ** ** ** ****** * ** ***

Plecturocebus      TTAGCCAACCTAGGATCATTAAATCTTCTAATAATACTATTTACCACTAAAGATATATTA
Callithrix         TTTAGCAATTTAGGGTCTCTAAACATTCTCACAATAACCATCAACACCAAAGAAACCGTA
Alouatta           TTAAGCAACCTAGGATCATTAAATATACTAATAATAA---TTAATACCAAAGAAATATTG
                   **   ***  **** **  ****  * ** * ****    * *  ** ***** *   * 

Plecturocebus      CTCTCCTGAACCAACTCTATTACGTGACTAGGATGTATACTAGCCTTTATAGTCAAAATA
Callithrix         CTGTCCTGAACCAACAACATTGTATGATTAGGGTGCATAATAGCCTTTATAGTCAAAATA
Alouatta           CTATCCTGAACTAATAACATCACATGACTAGGCTGTATAATAGCCTTTATAGTCAAAATA
                   ** ******** **    **    *** **** ** *** ********************

Plecturocebus      CCCCTTTACGGTCTTCACCTATGATTACCCAAAGCACACGTTGAAGCTCCCATTGCAGGC
Callithrix         CCTCTATACGGACTACACCTGTGACTCCCCAAAGCCCATGTTGAAGCCCCTATCGCCGGT
Alouatta           CCCTTATATGGACTTCACCTATGATTACCTAAGGCTCACGTTGAAGCTCCAATTGCTGGC
                   **  * ** ** ** ***** *** * ** ** ** ** ******** ** ** ** ** 

Plecturocebus      TCAATAGTTCTAGCAGCAATCTTACTAAAACTAGGAAGCTACGGCATAATACGAATTACT
Callithrix         TCAATAGTACTTGCAGCTATTTTACTAAAACTGGGTGGCTATGGTATAGTACGAATCACC
Alouatta           TCAATAGTACTTGCAGCAATTCTACTAAAACTTGGTGGCTACGGTATAATACGAATTACC
                   ******** ** ***** **  ********** **  **** ** *** ******* ** 

Plecturocebus      CCCATACTTAATCCCTTGACAGAAAAAATAAGCTACCCTTTCATCATCCTATCCCTATGA
Callithrix         CCTATGCTAAACCCCCTGACAGAAAAAATAAGTTATCCATTTATCGTTCTATCCCTGTGG
Alouatta           CCTATCCTCAACCCCCTAACAGAAAAAATAGGCTACCCCTTTCTCATTTTATCCCTATGA
                   ** ** ** ** *** * ************ * ** ** **  ** *  ******* ** 

Plecturocebus      GGGATAGTAATAACAAGCTCCATCTGCCTACGACAAGCCGACCTAAAATCTCTCATTGCC
Callithrix         GGCATGGTTATAACAAGCTCCATCTGCCTACGACAAGCAGACCTAAAATCACTCATCGCC
Alouatta           GGCATAGTTATAACAAGCTCGATCTGCTTACGACAAACTGACCTGAAATCACTCATCGCT
                   ** ** ** *********** ****** ******** * ***** ***** ***** ** 

Plecturocebus      TATTCCTCCGTTAGCCATATAGCACTGGTCATTCTAGCCATCCTTATCCAAACCCCTTGA
Callithrix         TATTCTTCCGTTAGCCACATAGCACTTGTTATCCTAGCCATTCTTATTCAAACTCCCTGA
Alouatta           TACTCCTCTGTAAGCCACATAGCACTTGTTATCTTAGCCATCCTCATTCAAACACCTTGA
                   ** ** ** ** ***** ******** ** **  ******* ** ** ***** ** ***

Plecturocebus      AGCTTTACCGGCGCTATTATCCTTATAATCGCCCATGGACTTACCTCATCCCTACTATTC
Callithrix         AGCCTCACCGGCGCCATAATTCTAATGATTGCCCACGGACTCACCTCATCCTTACTATTC
Alouatta           AGCTTTACCGGCGCAATAATCCTCATAATTGCCCATGGACTTACCTCATCCCTATTATTC
                   *** * ******** ** ** ** ** ** ***** ***** ********* ** *****

Plecturocebus      TGCCTGGCAAACTCAAACTATGAACGAATTCACAGCCGAACTATAATATTTACCCGAGGC
Callithrix         TGCCTTGCAAACTCTAACTACGAACGAGTCCACAGCCGAACAATAATATTTACACGAGGC
Alouatta           TGTCTAGCAAACTCAAACTACGAGCGAATCCACAGCCGAACTATAATATTTACCCGAGGC
                   ** ** ******** ***** ** *** * *********** *********** ******

Plecturocebus      CTACAAACACTATTTCCCCTCCTTGCCCTCTGATGACTTATAGCTAACCTCACCAACCTT
Callithrix         CTTCAAGCACTATTCCCACTACTAGCACTATGATGATTACTAGCCAATCTCACCAATCTT
Alouatta           CTCCAAGCACTATTTCCCCTACTAGCCCTTTGATGACTTCTGGCAAACCTCGCCAATCTC
                   ** *** ******* ** ** ** ** ** ****** *  * ** ** *** **** ** 

Plecturocebus      GCCCTACCCCCAACCATTAATCTAATAGGGGAGTTATTTACAATTATAGCCTCTTTCTCC
Callithrix         GCCCTACCCCCAACTATCAATTTAATGGGAGAGCTGCTAACAATTCTAGCCTCCTTCTCC
Alouatta           GCCCTACCCCCAACCATTAACCTGATAGGAGAACTATTCACAATCTTAGCCTCTTTCTCC
                   ************** ** **  * ** ** **  *  * *****  ******* ******

Plecturocebus      TGATCTAATTTTACCATTATATTCACAGGACTTAATATGCTAGTTACAGCTCTATACTCA
Callithrix         TGATCTAATTTCACCATCATATTCACAGGATTCAACATACTAATTACAGCTCTATACTCA
Alouatta           TGATCTAACTTTACTATTATATTTACAGGATTTAATATACTAATTACAGCCTTATACTCA
                   ******** ** ** ** ***** ****** * ** ** *** *******  ********

Plecturocebus      CTCCATATATTTACATCAACGCAACGAGGACCATTAACATACAGCACTAGTAATTTTAAG
Callithrix         CTTCACATATTTACTTCAACACAACGAGGTCCACTAACATATAGCACCAGCAATGTAAAA
Alouatta           CTTCACATATTTACCTCAACACAACGAGGACAACTAACGTATAGCACTAGTAATATCAAA
                   ** ** ******** ***** ******** * * **** ** ***** ** *** * ** 

Plecturocebus      CCCTTATTTACACGTGAAAATACTTTAATACTAATACACTTGGGACCAATTATCCTCCTC
Callithrix         CCCCTATTTACACGAGAAAACACACTTATACTAATGCACATAGCACCAATCCTTCTACTT
Alouatta           CCCCTCTTCACACGAGAAAATACACTAATACTAATGCATACAGCACCAATACTTCTCCTC
                   *** * ** ***** ***** **  * ******** **    * ******  * ** ** 

Plecturocebus      ACCCTAAACCCCAAAGTAATTATAGGTCCAACCCCCTGTAGCTATAGTTTAATTAAAACA
Callithrix         ACCCTAAACCCTAAAACAATTATATGCCTTACACCCTGTAGCTATAGTTTAACAAAAACA
Alouatta           ACCCTTAACCCCAAAGTGATTATAGGATTAGCACCTTGTAGTTATAGTTTAACAAAAACA
                   ***** ***** ***   ****** *     * ** ***** **********  ******

Plecturocebus      TTAGATTGTGAATCTAATATTAGAAGTTGATAACTTCTTATCTACCGAGAAAGTATGCAA
Callithrix         TTAGATTGTGAATCTAACAATAGAGGCTCGTAACTTCTTAACTACCGAGAAAGAATGCAA
Alouatta           TTAGATTGTGAATCTAACAATAGAGGCCTACAACTTCTTATCTACCGAGAAAGCACGCAA
                   ***************** * **** *     ********* ************ * ****

Plecturocebus      GAACTGCTAACTCATGCCCCCACGCTTAATTAGCCTGGCTTTCTCAACTTTTAAAGGATA
Callithrix         GAACTGCTAATTCATGCCCCCAGGCTTAA-CAACCTGGCTTTCCCAACTTTTAAAGGATA
Alouatta           GAACTGCTAATTCATGCCCCCAAGCTTAA-CAACTTGGCTTTCTCAACTTTTAAAGGATA
                   ********** *********** ******  * * ******** ****************

Plecturocebus      GAAGTTATCCATTGGTCTTAGGAACCAAAAATATTGGTGCAACTCCAAATAAAAGT-ATA
Callithrix         GCAGTTATCCGTTGGCCTTAGGAGCCAAAAACATTGGTGCAACTCCAAATAAAAGTAAAA
Alouatta           GCAGTTATCCATTGGTCTTAGGAACCAAAAACATTGGTGCAACTCCAAATAAAAGT--AA
                   * ******** **** ******* ******* ************************   *

Plecturocebus      ATGTTCTCCTCCATAACCCTAATAACACTAGCTCCTCTACTAGTACCTATTATAATTACC
Callithrix         ATACACTCTTCATTAATTCTAATAACGATAATTCCACTACTAACACCTATTATTATTACC
Alouatta           ATGTACTCCTCTACAATATTATTAATGCTAACCCCTCTATTAATACCTATTATAATCACC
                   **   *** **   **   ** ***   **   ** *** **  ********* ** ***

Plecturocebus      CTTATTAATCCTCGCAACAATCCCTTATACCCACACTACGTAAAACTGGCCATTGTATAC
Callithrix         TTAATTAAACCAAATAATAACCTCCTATACCCCTACTACGTAAAATTAGCCATCATTTAC
Alouatta           CTAATTAAACCCCACAAAAACACTTTGTACCCACACTATGTAAAATTAGCAATCATCTAT
                    * ***** **    ** **     * *****  **** ****** * ** **  * ** 

Plecturocebus      TCCCTCTCTATCAGCCTACTAGCCACAACTATATTCATTCTTACAGGCCAAGAATTTATA
Callithrix         GCTTTTATTATCAGCATACTATCAATAACAATATTCATCTTTACAGGCCAAGAATCTATA
Alouatta           GCCCTTATCGTTAGCATTTTAACTATAATAGTATTTATCTTTACAGGCCAAGAATCTATA
                    *  *     * *** *  ** * * **   **** **  *************** ****

Plecturocebus      ATTTCAAACTGACACTGAACAACTATTCAAACTATTAAATTATTTCTAAGCTTCAAAATA
Callithrix         GTCTCAAACTGACACTGAATAACTATCCAAACCATCGAGCTATCGCTAAACTTCAAGATA
Alouatta           ATCTCAAGCTGACACTGAACAACAATTCATACTATCAAATTATCCCTAAGTTTTAAACTA
                    * **** *********** *** ** ** ** **  *  ***  ****  ** **  **

Plecturocebus      GACTTTTTCTCTATAGTATTTACCCCCGTGGCACTACTTGTCACATGATCAATTGTTGAA
Callithrix         GACTTCTTCTCCACAATATTCACCCCTGTAGCATTATTTGTTACTTGATCTATCGTAGAA
Alouatta           GATTTCTTCTCCACCATATTTACCCCTGTAGCACTATTCGTCACCTGATCAATCGTAGAG
                   ** ** ***** *   **** ***** ** *** ** * ** ** ***** ** ** ** 

Plecturocebus      TTCTCAATATGGTATATACACTCTGACCCAAATATTAACCAATTTCTCAAGTACCTACTC
Callithrix         TTCTCTATATGATACATAAGCTCAGACCCAAACATCAACCGATTCCTTAAATACCTACTT
Alouatta           TTCTCAACATGATATATAAACTCAGACCCCAACATTAACCAATTCCTCAAATATTTACTC
                   ***** * *** ** ***  *** ***** ** ** **** *** ** ** **  **** 

Plecturocebus      ATTTTTCTTATTACTATAATTATCCTTATTACTGCTAATAATCTATTCCAACTTTTCATT
Callithrix         ATTTTCCTCGTAACAATATTAATTCTAATCACAGCTAACAATTTATTCCAACTCTTCGTC
Alouatta           ATCTTCCTTATCACTATATTAATTTTAATCACCGCTAATAACCTATTTCAACTCTTCATC
                   ** ** **  * ** *** * **  * ** ** ***** **  **** ***** *** * 

Plecturocebus      GGATGAGAAGGAATAGGCATTATATCCTTTCTGCTAATTGGCTGATGGCACGGTCGAACA
Callithrix         GGGTGAGAAGGAATGGGCATTATATCATTCCTACTGATCAGCTGATGGCACGGCCGTACA
Alouatta           GGATGAGAAGGAATAGGCATTATATCTTTTCTATTAATTAGCTGATGATACGGCCGATCA
                   ** *********** *********** ** **  * **  *******  **** **  **

Plecturocebus      GACGCTAATACAGCTGCATTGCAAGCAATCCTGTATAATCGCATTGGTGATATTGGGTTT
Callithrix         GACGCAAACACCGCAGCCCTACAAGCAATTCTATATAACCGAATTGGAGACATCGGTTTT
Alouatta           GACGCTAACACAGCAGCCCTTCAAGCAATCCTATATAATCGTATCGGAGATATCGGCTTT
                   ***** ** ** ** **  * ******** ** ***** ** ** ** ** ** ** ***

Plecturocebus      ATCCTGGCAATAGCATGATTTTTCCTATACGCCAACTCATGAGATTTTCAACAAATATTT
Callithrix         ATCCTGGCAATAACATGGTTCTTCCTATATTCCAACTCATGGGATTTCCAACAAATATTC
Alouatta           ATCTTAGCAATGGCATGATTCTTTATATTCTCAAACTCATGGGATTTTCAACAAATATTT
                   *** * *****  **** ** **  ***   * ******** ***** *********** 

Plecturocebus      ATTATTAATTTTACCCCAAGTTCTTTTCCCCTAATTAGCCTCCTTCTTGCCGCTACCGGA
Callithrix         ATTCTTGATAAAACCCCAAATTCTTTCCCACTAATAAGCCTCCTACTAGCAGCTACAGGA
Alouatta           ATCCTTAACCCCAACCCAGATCCCTTCCCCCTAGTAAGCCTTCTCCTGGCAGCAACAGGA
                   **  ** *    * ****  * * ** ** *** * ***** ** ** ** ** ** ***

Plecturocebus      AAGTCAGCTCAATTTGGCCTCCACCCATGACTCCCCTCCGCCATAGAAGGCCCTACCCCA
Callithrix         AAATCCGCCCAATTTGGCCTACACCCATGACTTCCATCCGCCATAGAAGGACCCACGCCA
Alouatta           AAATCAGCCCAATTTGGCCTCCACCCATGACTACCCTCCGCCATAGAAGGACCCACACCA
                   ** ** ** *********** *********** ** ************** ** ** ***

Plecturocebus      GTCTCAGCACTACTCCACTCCAGTACTATAGTAGTTGCGGGGATTTTCCTAATTATTCGA
Callithrix         GTCTCAGCATTACTACATTCAAGCACAATAGTTGTTGCAGGAGTCTTCCTAATTATTCGC
Alouatta           GTCTCAGCACTACTTCACTCCAGCACAATAGTTGTTGCCGGAATCTTCTTAATTATTCGC
                   ********* **** ** ** ** ** ***** ***** **  * *** ********** 

Plecturocebus      TTCCACCCCCTATTCGAAAATAATTTACCTATACAAACACTTACATTAACTCTAGGAGCT
Callithrix         TTCCACCCCATAATAGAAAATAACCCCTTTATTCAAACACTTACCCTATCAATAGGCGCA
Alouatta           TTTCACCCCTTAATTGAAAGTAACTTATCCATTCAAACACTCACACTATCACTAGGAGCT
                   ** ****** ** * **** ***       ** ******** **  ** *  **** ** 

Plecturocebus      ATCACTACCCTATTCACAGCTATCTGTGCTCTAACACAAAACGATATGAAAAAAATTATT
Callithrix         ATCACCACCCTATTTACAGCAATCTGTGCTCTAACACAAAATGACCTTAAAAAGATCGTA
Alouatta           ATTACTACCCTATTCACAGCAATCTGTGCCCTCACACAAAATGACATGAAAAAAATCGTA
                   ** ** ******** ***** ******** ** ******** **  * ***** **  * 

Plecturocebus      GCCTTCTCAACCTCAAGCCAACTGGGCCTTATAATAGTAACAGTTGGTCTTAACCAACCA
Callithrix         GCATTTTCAACCTCAAGCCAACTAGGCCTCATAATAGTAACAATCGGCATTAACCAACCA
Alouatta           GCCTTCTCAACTTCAAGCCAACTTGGCCTTATGATAGTAACAGTAGGCATTAACCAACCA
                   ** ** ***** *********** ***** ** ********* * **  ***********

Plecturocebus      TTTTTAGCTTTTCTTCACATCTGCACCCATGCCTTCTTTAAGGCCATACTATTTCTATCA
Callithrix         CACCTAGCATTCCTCCACATCTGCACCCATGCCTTCTTCAAAGCAATACTGTTCCTATCC
Alouatta           CATTTAGCCTTCCTTCACATTTGTACTCATGCTTTCTTCAAGGCCATACTATTTTTATCT
                       **** ** ** ***** ** ** ***** ***** ** ** ***** **  **** 

Plecturocebus      GCAGGATCTATTATTCATAACCTTAACAACGAACAAGATATCCGAAAAATAGGAGGTCTA
Callithrix         GCAGGATCTATCATTCACAGCCTAAACAACGAACAAGACATCCGCAAAATAGGAGGGCTA
Alouatta           GCAGGGTCTATTATCCACAGTCTCAATAACGAGCAAGACATCCGAAAAATAGGAGGCTTA
                   ***** ***** ** ** *  ** ** ***** ***** ***** ***********  **

Plecturocebus      TTTTATACCCTACCATTCACTGCTTCCTCTCTTATTATTGGCAATTTAGCACTTATAGGC
Callithrix         TTTAAAACTCTACCATTCACATCCTCCTCCCTCATTATTGGCAGCTTTGCACTCATAGGT
Alouatta           TTTAAAATATTACCATTCACTACCTCGTCCCTAGTCATCGGCAGCCTTGCACTCATGGGC
                   *** * *   **********  * ** ** **  * ** ****   * ***** ** ** 

Plecturocebus      ACACCCTTCTTAACAGGCTTCTACTCAAAAGATCTAATTATTGAAGCTGCCAATATATCA
Callithrix         ATACCCTTTCTCACAGGCTTCTACTCAAAAGACCTAATCATCGAAGCCGCCAACACGTCG
Alouatta           ATGCCTTTCCTCACGGGCTTCTACTCAAAAGACCTAATCATCGAAACCGCCAACATGTCG
                   *  ** **  * ** ***************** ***** ** *** * ***** *  ** 

Plecturocebus      TATACCAACGCCTGAGCCCTCATAATCACCCTAGTAGCCACCTCCCTTACAGCTGCATAC
Callithrix         TATACAAACGCCTGAGCCCTAACGACTACCTTGGTAGCCACCTCCCTTACAGCTATATAC
Alouatta           TATACCAACGCCTGAGCCCTTACAATTACCCTACTAGCAACCTCCCTCACAGCCATATAC
                   ***** ************** *  *  *** *  **** ******** *****   ****

Plecturocebus      AGCATTCGCATAATCTTCTTTACCCTCACAAACTACCCCCGATCTATTAGCCTAATACTA
Callithrix         AGTATCCGAATTATTTTCTTTGCCTTAACAGGATACCCTCGCTTTACAACTCTCATCTTA
Alouatta           AGCATTCGCATTATTTTCTACACTCTAACAGGATACCCCCGATTTACATCCCTTATCCTA
                   ** ** ** ** ** ****   *  * ***   ***** ** * **     ** **  **

Plecturocebus      ATTAACGAAAATAACCCCTTACTAATAAATCCAATTAACCGCCTAGCAATCGGAAGCATC
Callithrix         ATTAATGAAAATAACCCAAAACTAATAAACCCTATCAATCGCCTAGCACTGGGTAGCATT
Alouatta           ATTAATGAAAATAACCCCTCACTAATAAATCCTATTAACCGCTTAGCAGTGGGCAGCATC
                   ***** ***********   ********* ** ** ** *** ***** * ** ***** 

Plecturocebus      TTCGCTGGATTTCTTATCTCCAACTGTATTCCTCCTACCTACCACCCTCAAACAACCATA
Callithrix         TTCGCCGGGTTTCTTATTTCCAACTGTGTTCCTCCTACCTCACACCCCCAAGTCACTATA
Alouatta           TTCGCCGGATTTCTTATTTCCAACTGCATCCCTCCTACTTCATACCCCCAAGTCACCATA
                   ***** ** ******** ********  * ******** *   **** ***   ** ***

Plecturocebus      CCCCTCTACCTCAAACTAGCAGCCCTAGGAGTTACTATCCTAGGCCTTCTACTAGCTATA
Callithrix         CCATGACACCTAAAACTTATAGCCTTGGGCGTAACAATTCTAGGACTACTTGTAGCAACA
Alouatta           CCAACCCACCTTAAATTAGCAGCCCTAGGTGTGACTATTCTAGGACTTCTTATAGCAATA
                   **     **** *** *   **** * ** ** ** ** ***** ** **  **** * *

Plecturocebus      GAACTCAGCATTATAACCAATAATATAAAACTAAAAATCCCAGTAAAAACCTACTACTTT
Callithrix         GAACTTAGTTTAATAACTAACAATATAAAATTAAGCACCCCATTAAAAACATTCTACTTC
Alouatta           GAACTTAACCTAATAACCAATAATATAAAACTAAGCACCCCAGTAAAACCCTTCTACTTC
                   ***** *   * ***** ** ********* ***  * **** ***** * * ****** 

Plecturocebus      TCCAATATACTAGGATTTTACTCCACTACCACACACCGCCTAACCCCTCACTCAGGCCTA
Callithrix         TCCAACATACTAGGATTTTACTCAGCCACTACACACCGACTCAACCCACATTCAAGCCTT
Alouatta           TCCAACATATTAGGTTTCTACTCAATCACTACCCACCGATCAAATCCCCACTCAAGCTTA
                   ***** *** **** ** *****    ** ** *****    *  ** ** *** ** * 

Plecturocebus      ACTTCAAGCCAAAACCTTACATCCATATTGCTAGACTTACTCTGACTAGAAAAAACAATG
Callithrix         ACCATGAGCCAAAACCTTACCTCAGCCCTACTAGACCTATTCTGATTAGAAAAGTCTATG
Alouatta           ACCGCAAGCCAAAACTTTACCTCAGCCCTAATAGACCTATTCTGATTAGAAAAATCTATA
                   **    ********* **** **     *  ***** ** ***** *******  * ** 

Plecturocebus      CCAAAAATAACATCAATAACCCAAATTTCAATTTCCACCTCTACCTCAGCCCAAAAAGGC
Callithrix         CCAAAAATAACAGCACAGACCCAAATTTCAGCATCCACCACCTCATCAACTCAAAAAGGC
Alouatta           CCAAAAATAACAACACAAACTCAAATTTCAATCTCTACAACAGCATCAACCCAAAAAGGC
                   ************ **   ** *********   ** **  *  * *** * *********

Plecturocebus      CTAATCAAGCTCTACTTCCTATCGTTCTTTATTCCACCTACTCTTATACTACTCTTAGCC
Callithrix         CTAATTAAACTATACTTCCTATCCTTCTTCATCCCACCAATACTAGCACTTTTCCTAATA
Alouatta           TTAATCAAGCTCTACTTCTTATCATTCTTCATCCCACCCGCCCTAACATTTCTATTAATT
                    **** ** ** ****** **** ***** ** *****    **   * *  *  **   

Plecturocebus      ATCTAACCTCCACCCCGAGTTAGCTCAATAGCAATATGTATACCTGTAAACAATGCCCAA
Callithrix         ATTTAGCCCCCTCCCCGAGTAAGTTCAATTGCAATGTGCATTCCCATAAACAACGCCCAA
Alouatta           ATTTAACCCCCACCACGGGTAAGCTCAATCGCAATATGTATACCCATAAACAATGCCCAA
                   ** ** ** ** ** ** ** ** ***** ***** ** ** **  ******* ******

Plecturocebus      CAAGTAACTAAAACAACCCAAACCCCGTAGTTATACAATGCAGCTGCACCAGTAGGATCC
Callithrix         CAAGTCACTAAAACTACTCAAAACCCATAATTATATAAAGCAGCAGCACCTGTAGGATCC
Alouatta           CAAGTAACTAAAACAACTCAAACACCATAGCTATATAAAGCAGCAGCACCCGTAGGATCT
                   ***** ******** ** ****  ** **  **** ** ***** ***** ******** 

Plecturocebus      TCACGAATTAACCCAGGCCCTTCACCCTCATAAATCATTCAACTGGCCACAGTCTTATAA
Callithrix         TCACGAATCAACCCAGGCCCATCACCTTCATAAATTATCCAACTTGACACAGTGTTATAA
Alouatta           TCACGAACCAATCCTGGCCCATCACCTTCATAAATTATTCAACTAGACACAGTCTTATAA
                   *******  ** ** ***** ***** ******** ** ***** * ****** ******

Plecturocebus      TTTACAGTAACAGTCACACCCTCAACCGTCTTAATGGGATCCCCACCCAGCAAAAATACC
Callithrix         TTAATAACAA---------TCTCCACCGTTTTTACAGGATCCCCGCCCAACAAGAATACC
Alouatta           TTAACAGTAA---------CTTCTACCGTTTTATTAGGATCTCCACCCAATAAGGCTACC
                   ** * *  **           ** ***** **    ***** ** ****  **   ****

Plecturocebus      ATAGTAAACTCCATAACTAAACCTATTAATATAGTTCCCAAAATATCCATGCTTGATAGC
Callithrix         ATAGTTGCCTCTATCATTAAACCTAGCACAAAAATACCTAAAATATCTGCACTCGACACC
Alouatta           ATGGTTATCTCTATTACTAAGCCCAGTATAAAAATTCCTAAAATATCAATGCTTGACACC
                   ** **   *** ** * *** ** *  *  * * * ** ********    ** ** * *

Plecturocebus      CATGACTCAGGATGCTCATCAATTGCCATTGCTGCAGTATAACCAAAAACAACTATTATC
Callithrix         CACGTTTCAGGGTGCTCATCAATTGCTATGGCCGCAGTATAACCAAAAACTACCATTATA
Alouatta           CATGTCTCAGGATGCTCATCAATCGCCATCGCCGCAGTATAACCAAAAACAACCATCATA
                   ** *  ***** *********** ** ** ** ***************** ** ** ** 

Plecturocebus      CCACCCAAATAAATTAAAAAAACTATTAATCCCATATAAGACCCCCCTAAATATAATGTA
Callithrix         CCACCCAAATAAATCAAGAAAACCATAAGACCTAGGTAAGACCCACCAAAGTATAACGTA
Alouatta           CCACCTAAATAAACTAAAAAAACTATTAGCCCTATATAAGACCCACCAAAATATAATGTA
                   ***** *******  ** ***** ** *  ** *  ******** ** ** ***** ***

Plecturocebus      ATCGCACAACCCACAGCACCACTAAAAACTAACACCAAACCACCATAAATAGGCGAAGGC
Callithrix         ATAACACAACCTACAGCACCGCTAAAAATTAACACCAGCCCCCCATAAATAGGAGAAGGT
Alouatta           ATTGCACAACCCACAGCACCACTAAAAACCAACACCAACCCCCCATAGATAGGTGAAGGC
                   **  ******* ******** *******  *******  ** ***** ***** ***** 

Plecturocebus      TTAGAGGAAAATCCCATAAACCCCATTACTAGTATAATACTTAATGAAAATAAAGCATAT
Callithrix         TTAGAACAAAACCCCACAAATCCTATTACTAAAATAATACTTAATGAAAATAAAGCATAT
Alouatta           TTAGAAGAAAACCCCACAAACCCTATCACTAAAACAATACTTAATGAAAATAAAGCATAC
                   *****  **** **** *** ** ** ****  * ************************ 

Plecturocebus      GTCATTATTCCCACATGGATT-TAACCATGACTAATGATATGAAAAACCATTGTTGTGTT
Callithrix         GTCATTATTCCCACATGGGCTATAACCATGACTAATGATATGAAAAACCATCGTTGTACT
Alouatta           ATCATTATTCCCACATGGACTATAACCATGACTAATGATATGAAAAACCATTGTTGTATT
                    *****************  * ***************************** *****  *

Plecturocebus      TCAACTATAAGAATTCTAATGACCATAACCCGTAAAACACACCCGCTAGCAAAAATTATT
Callithrix         TCAACTATAAGAATCTTAATGACCTCTCCCCGTAAAACCCACCCACTAGCAAAAATCATC
Alouatta           TCAACTATAAGAATCTTAATGACTACTCCCCGCAAAACACATCCACTAGCAAAAATCATC
                   **************  *******     **** ***** ** ** *********** ** 

Plecturocebus      AACAACTCATTTATTGACCTACCCACACCATCCAACATCTCATCCTGATGAAATTTCGGC
Callithrix         AACGAGTCATTCGTCGACCTTCCCACGCCATCCAACATCTCCTCTTGATGAAACTTTGGC
Alouatta           AACAACTCATTTATTGATCTCCCTACACCATCCAACATCTCCGCCTGATGAAATTTCGGC
                   *** * *****  * ** ** ** ** **************  * ******** ** ***

Plecturocebus      TCACTTCTAGGTATCTGCCTTATTACTCAAATTGCCACCGGCCTATTTCTAGCCATACAT
Callithrix         TCACTTCTAGGCACCTGCCTAATTATTCAAATTACTACAGGCCTATTCCTAGCAATACAC
Alouatta           TCACTCCTAGGTATTTGCCTAATTATTCAAATCACTACAGGTCTATTCTTAGCCATACAC
                   ***** ***** *  ***** **** ******  * ** ** *****  **** ***** 

Plecturocebus      TACACGCCGGACACCTCCTCTGCCTTCTCCTCAGTAGCCCATATTACACGAGATGTAAAC
Callithrix         TACACACCAGACACCACTACCGCTTTCTCCTCAGTTGCCCACATCGCCCGAGACGTTAAC
Alouatta           TATACACCAGACACCTCAACTGCCTTCTCCTCAGTCGCCCACATCACCCGAGACGTCAAC
                   ** ** ** ****** *  * ** *********** ***** **  * ***** ** ***

Plecturocebus      TACGGCTGAATTATCCGTCACCTACATGCTAACGGCGCCTCCATATTTTTCATCTGCCTG
Callithrix         TACGGCTGAATAATCCGATACCTACATGCTAACGGCGCATCCATATTCTTTATCTGCCTA
Alouatta           TACGGCTGAATAATCCGCTACCTACACGCCAATGGCGCCTCCATGTTCTTCATCTGCCTC
                   *********** *****  ******* ** ** ***** ***** ** ** ******** 

Plecturocebus      TTTCTTCACATTGGACGAGGCCTGTACTATGGATCATTTCTCTTTCTGAAGACCTGAAAT
Callithrix         TTCCTCCACGTCGGCCGAGGGTTATATTACGGATCGTTCCTCTTTCTGAAGACTTGAAAC
Alouatta           TTCCTTCACATTGGCCGAGGCCTATATTATGGATCATTCCTTTTTCTGAAGACCTGAAAC
                   ** ** *** * ** *****  * ** ** ***** ** ** *********** ***** 

Plecturocebus      GTCGGTATTATCCTACTACTGGCATCTATAGCCACAGCATTTATGGGCTACGTACTTCCA
Callithrix         ATCGGTGCAATCTTACTACTTACTACCATGGCTACGGCATTTATAGGCTACGTACTACCA
Alouatta           ATCGGTATTATCCTTCTACTCACAACTATAGCCACAGCATTCATAGGCTATGTCCTCCCA
                    *****   *** * *****  *  * ** ** ** ***** ** ***** ** ** ***

Plecturocebus      TGAGGTCAAATATCCTTCTGAGGTGCCACAGTAATTACAAACCTTCTATCAGCTATTCCC
Callithrix         TGAGGCCAAATGTCATTCTGAGGGGCCACAGTAATCACAAACCTTCTTTCAGCCATCCCC
Alouatta           TGAGGCCAAATATCATTCTGAGGGGCCACAGTAATTACAAACCTCCTATCAGCCATCCCA
                   ***** ***** ** ******** *********** ******** ** ***** ** ** 

Plecturocebus      TACATCGGATCAGACCTCGTACAATGAATTTGAGGGGGCTTCTCCGTAGACAAAGCCACA
Callithrix         TACATTGGGTCCGACTTAGTCCAATGAATTTGAGGGGGGTTTTCAGTAGACAAAGCTACC
Alouatta           TACATCGGATCTGACCTCGTACAATGAATCTGAGGTGGTTTCTCAGTAGATAAAGCCACC
                   ***** ** ** *** * ** ******** ***** ** ** ** ***** ***** ** 

Plecturocebus      CTTACACGATTCTTTACTTTCCACTTTATTTTACCCTTTATTATTGCGGCCTTAGCTGCT
Callithrix         CTCACACGATTCTTCACCTTCCACTTTATTTTACCTTTCATCATCGCGGCTCTAGCCACC
Alouatta           CTTACACGATTTTTCACCTTTCACTTCATTCTACCCTTTATTATCGCTGCCCTAGCAACC
                   ** ******** ** ** ** ***** *** **** ** ** ** ** **  ****  * 

Plecturocebus      ATCCACCTTTTATTTCTGCATGACACAGGCTCCAATAACCCATCAGGATTAGTATCCAAC
Callithrix         ATTCACCTCCTATTTCTGCACGAAACAGGCTCAAGTAATCCGTCAGGAATTACCTCTGAA
Alouatta           ATCCACCTCTTGTTTCTGCATGAAACAGGATCAAGTAACCCATCAGGAATGACATCGGAC
                   ** *****  * ******** ** ***** ** * *** ** ****** *    **  * 

Plecturocebus      TCTGACAAAATCGTATTTCACCCCTACTACACAATTAAAGATATCCTAGGGTTAATCTTT
Callithrix         CCCGACAAAATCCCATTCCACCCCTACTATACAATTAAAGACATCCTCGGACTAACCTTT
Alouatta           CTCGACAAAATCACATTTCACCCCTACTATACAACCAAAGATATCCTAGGCCTAATTTTC
                      *********  *** *********** ****  ***** ***** **  ***  ** 

Plecturocebus      CTCCTTCTTCTCCTAATAAGTCTAACTCTATTTGCTCCTGACCTTCTAACTGACCCAGAC
Callithrix         CTACTCCTAGCCCTAACGAGCTTAACCCTATTCACACCCGACCTATTAACTGACCCAGAT
Alouatta           CTCCTCCTATGTCTAATAAGCCTGACCCTATTTTCACCTGACCTTCTAACCGACCCAGAT
                   ** ** **    ****  **  * ** *****  * ** *****  **** ******** 

Plecturocebus      AACTATACCCTAGCAAATCCCCTTAATACCCCTCCCCACATTAAACCAGAATGATACTTC
Callithrix         AACTATACACTAGCAAACCCCCTAAACACCCCACCCCACATCAAGCCAGAGTGATACTTC
Alouatta           AATTATACACTAGCCAATCCCCTCAACACTCCACCCCACATTAAACCAGAGTGGTACTTC
                   ** ***** ***** ** ***** ** ** ** ******** ** ***** ** ******

Plecturocebus      CTATTTGCATATGCCATTCTACGATCCATCCCCAATAAGTTAGGAGGTGTTCTAGCCCTT
Callithrix         TTGTTCGCATATGCAATCCTACGGTCCATCCCCAATAAACTAGGAGGGGTCCTAGCCCTA
Alouatta           CTATTTGCATACGCAATCCTACGATCTATTCCTAACAAACTAGGAGGTGTCCTAGCCCTA
                    * ** ***** ** ** ***** ** ** ** ** **  ******* ** ******** 

Plecturocebus      ATTCTCTCTATCCTAATTCTAGCAATTATTCCTATAATCCATCTATCTAAACAACAAAGT
Callithrix         GCAATATCTATCCTGGTCCTAATAATCATCCCCATAACACACATATCCAAACAACAAAGC
Alouatta           GTACTCTCCATCCTAATCCTTATAATTATCCCTACCCTCCACCTATCAAAGCAACAAAGC
                       * ** *****  * **   *** ** ** *     **  **** ** ******** 

Plecturocebus      ATAATATTCCGACCAATTGGTCAAAGCCTATTCTGAACCCTAGCGGCCATTCTACTTACA
Callithrix         ATAACATTCCGACCAATTACCCAGACCATATTCTGGACACTAGTGGCTGACCTATTAACT
Alouatta           ATAGGATTCCGACCCATCACCCAAATCCTATTCTGAACTCTAGTAGCCGACCTATTCACA
                   ***  ********* **    ** * * ******* ** ****  **    *** * ** 

Plecturocebus      CTCACATGAATTGGAGGCCAACCAGTAGAATACCCCTTCGTAATTATTGGTCAAATAGCA
Callithrix         CTCACATGAATCGGAGGTCAGCCAGTAGAACACCCATTTATCGCTATTGGCCAGACAGCT
Alouatta           CTCACATGAATCGGAGGCCAACCAGTTGAATACCCCTTCATTACTATTGGCCAAACCGCA
                   *********** ***** ** ***** *** **** **  *   ****** ** *  ** 

Plecturocebus      TCCATTATATATTTTCTCACCATTATTACCCTTATTCCTCTATCCTCCTTAATTGAAAAT
Callithrix         TCTATCATATATTTTCTCATCATCATCACCCTAATTCCCCTCTCCGCTCTTATCGAAAAC
Alouatta           TCCATCATATATTTTCTCACTATCATTACACTTATTCCCCTCTCTGCCCTAATTGAAAAC
                   ** ** *************  ** ** ** ** ***** ** **  *  * ** ***** 

Plecturocebus      AAACTACTCAAATGGTAG-CGTCCTTGTAGTATAAGCCAATACCTCGGTCTTGTAAACCG
Callithrix         AAACTACTGAAGTGATAAAAGTCCTTGTAGTATAAACTATTACTCTGGTCTTGTAAACCA
Alouatta           AAACTACTTAAATGATAGACGTCTTTGTAGTATAATAGAATACCCCGGTCTTGTAAACCA
                   ******** ** ** **   *** ***********   * ***   ************* 

Plecturocebus      GATAACGGAGAAC-CTTACTCCCCAGGACACTTCAGGGAGAGAACATCCTGTTCTACAAT
Callithrix         GA-AATGGAGAATACCTACTCCCAAGGACAC-TCAAGAAGAGAATATTTAATTCCACCGT
Alouatta           GA-AATGGAGAA--CTCTCTCCCCAAGACATCTCAGGGAAAGAATCACCCATTCTACCTT
                   ** ** ******  *   ***** * ****  *** * * ****       *** **  *

Plecturocebus      CAGCACCCAAAGCTGAAATTCTAA-CTTAAATTACTCCCTG-----------CGCTTTAT
Callithrix         CAACACCCAAAGCTGATATTCTAGTATTAAACTACTCCTTGG----------TGCCTTCT
Alouatta           CAACACCCAAAGCTGAAATTCTAATCTTAAACTACTCCCTGAACACCAAACCAACCTTAT
                   ** ************* ******   ***** ****** **             * ** *

Plecturocebus      TTTCT-TTGAGTGCACAACTTTCAAGTACCATACAAGTA---CTTACATTTACAATATTA
Callithrix         CCTTTATTGATGGACTAGCAATGAAGTACTTTACAAGCATACGTAGCGTTTACAA-----
Alouatta           A--CTATTGAAAGCCTTACCACAGAGTACTTTACAGGTAAATCAAACATC----------
                       * ****  *     *     *****  **** * *       * *           

Plecturocebus      TTTCCTCCTTCATTATGTATATAGTACATTAATGCTTTACCCCATGTCTAATATATAGTA
Callithrix         --------ACTCCTATGTAATTTGTGCATTAATGCTTTGCCACATGAATAATATATAGTA
Alouatta           ------CCATCCGTATGTAATTAGTGCATTATTGCTTGCCCCCACGAATAATACATAGTA
                                ******  * ** ***** *****  ** ** *  ***** ******

Plecturocebus      CTATACATGCTTGATCATACATAGCACATGCCTCACAAGCCTCCCCTACCTACGATTACA
Callithrix         TTAACCATGCTTGACTATACATAGTACATA------AAACTTCA---ATGTACAGTAGAA
Alouatta           CTAGAAATGCTTAACTATACATAGCACATTACTCACAAA--------ACATGC-ATTAAA
                    **   ****** *  ******** ****       **         *  * *  *   *

Plecturocebus      -------AGACATGCTTATAAGCACGGATTTAATATTATTGACAGGACCA-AATACATAA
Callithrix         TCCTTACAGACATGCTTACAAGCAAGAATTAACTA-CGTAAACCGGACCATAACCTATAA
Alouatta           ACATTCTCAACATGCTTACAAGCAAGGATCATAAA-CCTATAAGAAACCATAACACACCA
                            ********* ***** * **     *   *  *    **** **   *  *

Plecturocebus      CTACCT---------TAATTCCCCGTAAATTATTACCCCCAT-----GGATA-----TCA
Callithrix         AATTCTCACACCACATAACTGCTCG-AAAACATGACTATTATCCTCCAAATAAAATGTTA
Alouatta           AATCTA---------AAACTGTACT-AAAGCATTAAGCCCAGCGTACGAATA-----TTA
                                   ** *   *  ***  ** *     *        ***     * *

Plecturocebus      TTTACCCCACCTTTGCTTAACTGTACATA-------CGCACATC--TCGTCTATGGTTCA
Callithrix         GCTAGTACAT----------CAGTACATG-------CAGATATTAATCGAACATAGTACA
Alouatta           CATAGTACATGCATTTATAACAGTACATAGTACATTAATCTATTGATCGCACATAGCACA
                     **   **           * ******             **   ***   ** *  **

Plecturocebus      TCC---------------------------------------------------------
Callithrix         TTA---------------------------------------------------------
Alouatta           TTCGTCCCGTAAGCCCTCCCCAGCTAGGGTACTCTTGTCGTACTATTTAACCCTACCACA
                   *                                                           

Plecturocebus      CATTCTAATTAA-----CCCCTTCA---ACATGGATATTCCTCCGTT--CAATTGGTCTC
Callithrix         ---------AAAAGAGGTATCGTCCGGTACATGGATATCCAACAGGTA-TTCTTGGTCTC
Alouatta           CATTCTACTAAATAAGTCCTTGTCA---ATACGGATATCCATCTTATACTGTTTGGTCTC
                             **          **    * * ****** *  *   *     ********

Plecturocebus      TTAATCCAACATCCTCCGTGAAACCAACATTCCATCCACAACCCTTACTA--ATTCTCGC
Callithrix         TTAATCTACCAACCTCCGTGAAACCAGCAACCCGCCCACA---TCTACTAGTATTCTCGC
Alouatta           TTAATCTACCATCCTCCGTGAAACCAACAACCCGCCCACA--CTTTACTGCTCTTCTCGC
                   ****** * ** ************** **  **  *****     ****    *******

Plecturocebus      CGGAAGCCCACGTC-ATGAAGAGTAACTATCCTCAAGCTGTAAACGGCATCTGGTTCCTA
Callithrix         TCCGGGCCCATATAGACAGGGCTTGGTTATCCTGAAACTATACCTGGCATTTGGTTCCTA
Alouatta           TCCGGGCCCATATAGACAGGGCTTGGTTATACTGAAACTATATCTGGCATTTGGTTCCTA
                        *****  *  *    *  *   *** ** ** ** **   ***** *********

Plecturocebus      CCTCAGGTACATATCATGTAATTCGCCCATACGTTCCCCTTAAATGAGACATTTGTGATG
Callithrix         CCTCAGGGCCATTTAACTAAGTCCGCACATACGTCCCCCTTAAATAAGACA-TCACGATG
Alouatta           CCTCAGGGCCATACCCTTAAGATCGCATATACGTTCCTCTTAAATAAGACA-TCACGATG
                   *******  ***       *   ***  ****** ** ******* ***** *   ****

Plecturocebus      GATCACGGTGCTGTCACCCTCTTAGCC-GGTCTACGGGAGCTCGATCCGCTATGGCCTAC
Callithrix         G--TGTGGCGCTATCTCCCTCTC-----GTTCTCGCGTCACTGGATGCATGGGTGCCT-C
Alouatta           G--TGTGGCGCTATCACCCTTTTAACCTGGTC----AGGAATGCACGCAAGAGGGCCT-T
                   *     ** *** ** **** *      * **         *  *  *      ****  

Plecturocebus      TGAGTAGGG-----ATGTACTCATCACCATTGCCTAGCCGGGAGTGGAATCCCTCTGGCT
Callithrix         TG-GTAGGAAAGGAATGTACTCATCAGCATCGTC-----------GAAAGACTCCTGGA-
Alouatta           TATGGGGGAGGGTTATGTACTCCTCAGCATTGCC-----------GTAGG----CTGGAG
                   *  *  **      ******** *** *** * *           * *      ****  

Plecturocebus      GAA----TCCCGCCGAT-ATCTGGTTAAGCTGGGACATGGCAGTGTTTGCCCCCTATTTA
Callithrix         -AAGAGGTTCCAATTATCATCCTGTAGCACCTGACTGTG-----ATTTG--CCAGACTTT
Alouatta           GAAAAGGTTCCAACGATAATCCTGTAGCGCCTGAATGTG-----ATTTG--CCAGACTTT
                    **    * **    ** ***  **    *  *    **      ****  **  * ** 

Plecturocebus      ATGGTGTCATTGTAGCAC-----GAATAGTTTGGCCCCCATCCC-ACCCATAAGGTGTTA
Callithrix         ATGCTATCATCGCGCCTGGTATTGAATGTCTTGGCCCCCAACCC-GCCCCCAAGGTGCTA
Alouatta           ATGCTGTCATCGCGCCTCTGATTGAATGTCTTGGCCCCCATCCCGGCCACTAAGGTGCTA
                   *** * **** *   *       ****   ********** ***  **   ****** **

Plecturocebus      TTCAGTCAATGGTCACAGGACATAAAAG----------------------AAAAAATTTT
Callithrix         TTCAATTCATGGTTTCAGGACATAACAAGCGAATTATTTGGCACCCCGCCAAAAAATTTA
Alouatta           TTCAGTTAATGGTTACAGGACATAAAAAGTAATTTTACCAACACCACGCCCAAAA-----
                   **** *  *****  ********** *                        ****     

Plecturocebus      ACCATTATTTACATTTAA--AATAAATTTATGCAAATTTAAACCCAAAATGCAACCCGCT
Callithrix         AATTTTAACCACCCGCTACCAATATATTTACTC-CATTAGAACCCAAAATTAAACCCAC-
Alouatta           ----TCACCCACACACCACCAAAAAACCTA----------ACCCCTAAGCCAGACACACC
                       * *   **     *  ** * *  **          * *** **     ** * * 

Plecturocebus      AACCCACACTTTCTGAGGTAACCACCGTAAAGAGACATCCGCCTACTAACATTTTT----
Callithrix         -------ATTCTCTGAGGCATGTATCACAAAGAGATAACCCACTATTGCCCCACTA----
Alouatta           TGGCTAAACTTTCTGAGGCGCGTATCGTAAAGAGACACCCCCCTACCAATATATTCACTA
                          * * *******     * *  ******* * **  ***         *     

Plecturocebus      -TTTATCACTTGAGAAATTACCCAGCAACAAATATTTACAATTAATATTTCACCGTACCC
Callithrix         ---------TTAAGCAA------AGCCTCCCACCTTAACACACATTACTAAATCGCTA--
Alouatta           GTTTAATATCTAAAAGACACATGGACCCTACAACCTCACATAATCTAATAAATAGTAC--
                             * *   *        *     *   * ***     ** *  *  *     

Plecturocebus      TTCCACCAATATTTACTTGTAATTTCTTCCCACACACCCAGGGCTATACCCCTCAGAAAG
Callithrix         -------------TATAAACTGTTACTCCTCGCATACCTCAAACGATGCCCTTCAGAGAA
Alouatta           -------------TACCCCTGATTACTTCCCACACACCTCAAAACATATCCTTCAGAAAG
                                **       ** ** * * ** ***       **  ** ***** * 

Plecturocebus      CATATTAGTACTAATACTACAGTAAAAAGAATTAATTTACCCAACCTCCCACCTTGACAC
Callithrix         TGTACTAATACTAACAC------AGCAGGAA-----------------------------
Alouatta           CATACTTATACTTGTAC------AATAAAAATCAAATCTAATAAACCACTACCTAAGCAC
                     ** *  ****   **      *  *  **                             

Plecturocebus      ACTCCACCCCAACAATTATCAA
Callithrix         ----------------------
Alouatta           ACCACAC------------TAA
                                         
